Repository home-assistant/addons, pull requests merged in 2018-10, with the labels that each got.

#418 Fix timezone && update 3.37.8
  homematic/CHANGELOG.md
  homematic/Dockerfile
  homematic/build.json
  homematic/config.json
Labels: cla-signed, in progress

#420 Update smb.conf
  samba/CHANGELOG.md
  samba/config.json
  samba/run.sh
  samba/smb.conf
Labels: cla-signed, in progress

#425 Sync time of RF Daemon every 30min
  homematic/CHANGELOG.md
  homematic/config.json
  homematic/run.sh
Labels: cla-signed

#429 Grammar fixes
  README.md
Labels: Hacktoberfest, cla-signed

#435 Store hmip_address.conf
  homematic/CHANGELOG.md
  homematic/Dockerfile
  homematic/config.json
  homematic/crRFD.conf
  homematic/run.sh
Labels: cla-signed, in progress
