Repository home-assistant/addons, pull requests merged in 2018-12, with the labels that each got.

#475 Support the changes in specific files without restarting home assistant
  git_pull/CHANGELOG.md
  git_pull/config.json
  git_pull/run.sh
Labels: cla-signed, in progress

#481 git_pull: fix for home-assistant/hassio-addons#480
  git_pull/CHANGELOG.md
  git_pull/config.json
  git_pull/run.sh
Labels: cla-signed

#482 Update HomeMatic OCCU to version 3.41.11
  homematic/CHANGELOG.md
  homematic/build.json
  homematic/config.json
Labels: cla-signed, in progress

#483 Homematic OCCU: Fix write error when starting OCCU due to missing status directory
  homematic/Dockerfile
Labels: cla-signed

#484 Homematic OCCU: Supply custom log4j configuration for HMIPServer to log to console
  homematic/Dockerfile
  homematic/log4j.xml
Labels: cla-signed

#458 Version Change Only - Snips 0.60.1
  snips/CHANGELOG.md
  snips/build.json
  snips/config.json
Labels: cla-error, cla-signed, in progress

#485 Homematic v8.0
  homematic/CHANGELOG.md
  homematic/Dockerfile
  homematic/build.json
  homematic/config.json
  homematic/log4j.xml
Labels: cla-signed, in progress

#486 git_pull: correct technical error in CHANGELOG
  git_pull/CHANGELOG.md
Labels: cla-signed

#488 Improve wording in Git Pull output
  git_pull/run.sh
Labels: cla-signed

#490 Show the installed homeassistant version in check_config
  check_config/run.sh
Labels: cla-signed

#491 Homematic: Fix InterfacesList.xml exception
  homematic/Dockerfile
Labels: cla-signed, in progress

#494 0.60.8
  snips/CHANGELOG.md
  snips/Dockerfile
  snips/build.json
  snips/config.json
  snips/run.sh
  snips/snips-entrypoint.sh
Labels: cla-signed, in progress
