Repository home-assistant/addons, pull requests merged in 2019-06, with the labels that each got.

#587 cec_scan: Refactor of add-on, added README
  cec_scan/CHANGELOG.md
  cec_scan/Dockerfile
  cec_scan/README.md
  cec_scan/config.json
  cec_scan/run.sh
Labels: cla-signed

#586 Refactor of check_config add-on
  check_config/CHANGELOG.md
  check_config/Dockerfile
  check_config/README.md
  check_config/config.json
  check_config/run.sh
Labels: cla-signed

#590 dhcp_server: Refactor
  dhcp_server/CHANGELOG.md
  dhcp_server/Dockerfile
  dhcp_server/README.md
  dhcp_server/config.json
  dhcp_server/dhcpd.conf
  dhcp_server/run.sh
Labels: cla-signed

#594 check_config: Additional information in log output to avoid confusion
  check_config/run.sh
Labels: cla-error, cla-signed, enhancement

#597 check_config: Bumped version to 2.1, updated CHANGELOG
  check_config/CHANGELOG.md
  check_config/config.json
Labels: cla-signed

#591 dnsmasq: Refactor
  dnsmasq/CHANGELOG.md
  dnsmasq/README.md
  dnsmasq/apparmor.txt
  dnsmasq/config.json
  dnsmasq/run.sh
Labels: cla-signed

#589 deconz: Updates README, fixes incorrect add-on link
  deconz/CHANGELOG.md
  deconz/README.md
  deconz/config.json
Labels: cla-signed

#596 tellstick: Refactor of add-on
  tellstick/CHANGELOG.md
  tellstick/Dockerfile
  tellstick/README.md
  tellstick/config.json
  tellstick/run.sh
Labels: cla-signed

#598 ssh: Refactor, bumped to 5.5
  ssh/CHANGELOG.md
  ssh/Dockerfile
  ssh/README.md
  ssh/config.json
  ssh/run.sh
Labels: cla-signed

#600 dhcp_server: Fixes crash when using FQDN as domain
  dhcp_server/CHANGELOG.md
  dhcp_server/config.json
  dhcp_server/run.sh
Labels: bug, cla-signed

#602 ssh: Fixes crash when using authorized keys
  ssh/CHANGELOG.md
  ssh/Dockerfile
  ssh/config.json
  ssh/run.sh
Labels: bug, cla-signed

#601 Fix mqtt pw generator
  mosquitto/Dockerfile
  mosquitto/config.json
  mosquitto/run.sh
Labels: cla-signed

#604 Bump Deconz to 2.05.65
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#605 Error correction deconz installation instructions
  deconz/README.md
Labels: cla-signed

#606 deconz: Bumps version to 2.5
  deconz/CHANGELOG.md
  deconz/config.json
Labels: cla-signed

#608 Fixes deconz otau download issues
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/config.json
  deconz/data/run.sh
Labels: cla-signed

#611 ⬆️ Deconz: bump to 2.05.66
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#612 SSH update + version pin
  ssh/CHANGELOG.md
  ssh/Dockerfile
  ssh/build.json
  ssh/config.json
  ssh/data/motd
  ssh/data/run.sh
  ssh/data/sshd_config
Labels: cla-signed

#615 deconz: Adds VNC & debug controls
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/README.md
  deconz/config.json
  deconz/data/run.sh
Labels: cla-signed

#616 deconz: Removes incorrect about section from readme
  deconz/README.md
Labels: cla-signed

#617 deconz: 3.1: VNC Port check & desktop name + firmware upgrade docs
  deconz/CHANGELOG.md
  deconz/README.md
  deconz/config.json
  deconz/data/run.sh
Labels: cla-signed

#619 deconz: Add reference to manual firmware upgrade procedure
  deconz/README.md
Labels: cla-signed
