Repository home-assistant/addons, pull requests merged in 2019-11, with the labels that each got.

#812 Remove unsupported architectures from Homematic README
  homematic/README.md
Labels: cla-signed

#809 Add documentation to the mariadb add-on
  mariadb/README.md
Labels: cla-signed

#814 Spelling and grammar fixes
  almond/README.md
  cec_scan/README.md
  check_config/README.md
  check_config/data/run.sh
  configurator/README.md
  deconz/CHANGELOG.md
  deconz/README.md
  dhcp_server/README.md
  dnsmasq/README.md
  git_pull/README.md
  homematic/README.md
  homematic/data/hm-firmware.sh
  letsencrypt/README.md
  mariadb/README.md
  mosquitto/data/run.sh
  samba/README.md
  snips/README.md
  ssh/README.md
  tellstick/README.md
Labels: cla-signed

#813 Update deconz 2.05.70
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: add-on: deconz, cla-signed

#817 Assist
  .hadolint.yaml
  ada/Dockerfile
  ada/README.md
  ada/azure-pipelines.yml
  ada/build.json
  ada/config.json
  ada/data/run.sh
Labels: cla-signed

#819 Ada02
  ada/CHANGELOG.md
  ada/README.md
  ada/azure-pipelines.yml
  ada/build.json
  ada/config.json
Labels: cla-signed

#822 Update Almond + Ada
  ada/CHANGELOG.md
  ada/build.json
  ada/config.json
  almond/CHANGELOG.md
  almond/Dockerfile
  almond/build.json
  almond/config.json
Labels: cla-signed

#821 Add Reddit to DuckDNS login options
  duckdns/README.md
Labels: cla-signed

#826 New deconz.dresden-elektronik.de subdomain
  deconz/Dockerfile
Labels: add-on: deconz, cla-signed

#831 Update almond 1.7.1
  almond/CHANGELOG.md
  almond/build.json
  almond/config.json
Labels: cla-signed

#832 Update Ada 0.5
  ada/CHANGELOG.md
  ada/build.json
  ada/config.json
Labels: cla-signed

#767 Adding config option for bash_profile in SSH
  ssh/CHANGELOG.md
  ssh/config.json
  ssh/data/run.sh
Labels: Hacktoberfest, add-on: ssh, cla-signed

#833 Fix addon name
  ada/README.md
Labels: add-on: ada, cla-signed

#829 Additional audioServer topics created by Snips platform
  snips/CHANGELOG.md
  snips/config.json
  snips/run.sh
Labels: add-on: snips, cla-signed

#844 almond: tag the Home Assistant skill as hassio-configured
  almond/CHANGELOG.md
  almond/config.json
  almond/data/run.sh
Labels: add-on: ada, cla-signed

#843 Deconz update 2.05.71
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: add-on: deconz, cla-signed

#846 Fix build, using new GPG keys from Snips
  snips/Dockerfile
Labels: add-on: snips, cla-signed

#848 Update ADA 0.7
  ada/build.json
  ada/config.json
  ada/data/run.sh
  almond/config.json
Labels: cla-signed

#853 Update configurator to 0.3.7
  configurator/CHANGELOG.md
  configurator/build.json
  configurator/config.json
Labels: cla-signed
