Repository home-assistant/addons, pull requests merged in 2019-09, with the labels that each got.

#683 Fix check config library
  check_config/CHANGELOG.md
  check_config/Dockerfile
  check_config/build.json
  check_config/config.json
Labels: cla-signed

#684 Cleanup some udev rules
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/config.json
  deconz/data/run.sh
Labels: cla-signed

#649 update deCONZ
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/build.json
  deconz/config.json
Labels: add-on: deconz, cla-signed

#692 Bump deCONZ 2.05.69 & wiringPi 2.52
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/build.json
  deconz/config.json
Labels: add-on: deconz, cla-signed

#686 logging for sshd DEBUG -> INFO
  ssh/CHANGELOG.md
  ssh/config.json
  ssh/data/sshd_config
Labels: cla-signed

#693 Update nginx.conf fix nginx: [warn] the "ssl" directive is deprecated
  nginx_proxy/CHANGELOG.md
  nginx_proxy/config.json
  nginx_proxy/data/nginx.conf
Labels: cla-signed

#592 configurator: Add git SSH support
  configurator/CHANGELOG.md
  configurator/Dockerfile
  configurator/README.md
  configurator/config.json
  configurator/data/run.sh
Labels: cla-signed

#697 Added an optional Cloudflare mechanism for real visitor ip
  nginx_proxy/CHANGELOG.md
  nginx_proxy/Dockerfile
  nginx_proxy/config.json
  nginx_proxy/data/nginx.conf
  nginx_proxy/data/run.sh
Labels: cla-signed

#704 Add homematic regahss support
  homematic/CHANGELOG.md
  homematic/Dockerfile
  homematic/build.json
  homematic/config.json
  homematic/data/config/HMServer.conf
  homematic/data/config/InterfacesList.xml
  homematic/data/config/crRFD.conf
  homematic/data/config/hs485d.conf
  homematic/data/config/log4j.xml
  homematic/data/config/rega.conf
  homematic/data/config/rfd.conf
  homematic/data/hm-interface.sh
  homematic/data/run.sh
Labels: cla-signed

#708 Optimize Homematic 9.x
  homematic/CHANGELOG.md
  homematic/Dockerfile
  homematic/config.json
  homematic/data/config/InterfacesList.xml
  homematic/data/hm-interface.sh
  homematic/data/run.sh
Labels: cla-signed

#701 Added DNS challenge support
  letsencrypt/CHANGELOG.md
  letsencrypt/Dockerfile
  letsencrypt/README.md
  letsencrypt/build.json
  letsencrypt/config.json
  letsencrypt/run.sh
Labels: cla-signed

#712 Small fix for LE
  letsencrypt/CHANGELOG.md
  letsencrypt/build.json
  letsencrypt/config.json
Labels: cla-signed

#714 Fix issue #709 - //empty function not required
  letsencrypt/CHANGELOG.md
  letsencrypt/README.md
  letsencrypt/config.json
  letsencrypt/run.sh
Labels: cla-signed

#623 Add cafile and require_certificate options
  mosquitto/CHANGELOG.md
  mosquitto/config.json
  mosquitto/data/run.sh
Labels: addon: mosquitto, cla-signed

#739 Create README.md
  samba/README.md
Labels: add-on: samba, cla-signed

#720 Exempt "Help wanted" from Stale bot
  .github/stale.yml
Labels: cla-signed

#745 Move log message
  check_config/CHANGELOG.md
  check_config/config.json
  check_config/data/run.sh
Labels: Hacktoberfest, add-on: check_config, cla-signed
