Repository home-assistant/addons, pull requests merged in 2020-04, with the labels that each got.

#1203 Fix start_supervisor.sh file permission
  .devcontainer/start_supervisor.sh
Labels: cla-signed

#1219 Update cli & fix s6-overlay shutdown
  mariadb/CHANGELOG.md
  mariadb/Dockerfile
  mariadb/config.json
  ssh/CHANGELOG.md
  ssh/build.json
  ssh/config.json
Labels: cla-signed

#1216 Remove advanced flag from SSH add-on
  ssh/config.json
Labels: cla-signed

#1220 Revert "Remove advanced flag from SSH add-on"
  ssh/config.json
Labels: cla-signed

#1208 samba: Support link-local IPv6 by default
  samba/CHANGELOG.md
  samba/README.md
  samba/config.json
Labels: cla-signed

#1227 almond: Rewrite/optimize Almond add-on
  almond/CHANGELOG.md
  almond/Dockerfile
  almond/build.json
  almond/config.json
  almond/data/run.sh
  almond/rootfs/etc/cont-init.d/almond.sh
  almond/rootfs/etc/nginx/nginx.conf
  almond/rootfs/etc/services.d/almond/discovery
  almond/rootfs/etc/services.d/almond/finish
  almond/rootfs/etc/services.d/almond/register
  almond/rootfs/etc/services.d/almond/run
  almond/rootfs/etc/services.d/nginx/finish
  almond/rootfs/etc/services.d/nginx/run
Labels: cla-signed

#1229 configurator: Version 5.0.0
  configurator/CHANGELOG.md
  configurator/Dockerfile
  configurator/build.json
  configurator/config.json
  configurator/rootfs/etc/configurator.conf
  configurator/rootfs/etc/services.d/configurator/finish
  configurator/rootfs/etc/services.d/configurator/run
  configurator/rootfs/root/.ssh/config
Labels: cla-signed

#1235 Fix Google Assistant SDK description
  google_assistant/README.md
Labels: add-on: google_assistant, cla-signed

#1241 almond: Keep unzip dependency installed
  almond/CHANGELOG.md
  almond/Dockerfile
  almond/config.json
Labels: add-on: almond, cla-signed

#1244 samba: Compatibility mode & upgrades
  samba/CHANGELOG.md
  samba/Dockerfile
  samba/README.md
  samba/build.json
  samba/config.json
  samba/data/run.sh
  samba/rootfs/etc/cont-init.d/samba.sh
  samba/rootfs/etc/samba/smb.conf
  samba/rootfs/etc/services.d/nmbd/finish
  samba/rootfs/etc/services.d/nmbd/run
  samba/rootfs/etc/services.d/smbd/finish
  samba/rootfs/etc/services.d/smbd/run
Labels: add-on: samba, cla-signed

#1255 Add a note about advanced mode
  ssh/README.md
Labels: cla-signed

#1263 check_config: Version 3.3.0
  check_config/CHANGELOG.md
  check_config/build.json
  check_config/config.json
  check_config/rootfs/etc/services.d/check-config/finish
  check_config/rootfs/etc/services.d/check-config/run
Labels: cla-signed
