Repository home-assistant/addons, pull requests merged in 2020-09, with the labels that each got.

#1458 Improves Terminal & SSH Add-On documentation
  ssh/DOCS.md
Labels: add-on: ssh, cla-signed

#1568 SSH: update cli & overwrite commands
  ssh/CHANGELOG.md
  ssh/build.json
  ssh/config.json
  ssh/rootfs/etc/fix-attrs.d/cli
  ssh/rootfs/etc/fix-attrs.d/profile
  ssh/rootfs/etc/fix-attrs.d/ssh
  ssh/rootfs/usr/local/bin/reboot
  ssh/rootfs/usr/local/bin/shutdown
Labels: cla-signed

#1569 SSH / SMB - media folder
  samba/CHANGELOG.md
  samba/build.json
  samba/config.json
  samba/rootfs/etc/samba/smb.conf
  ssh/CHANGELOG.md
  ssh/config.json
Labels: cla-signed

#1570 Check-Config: Update base image & media folder
  check_config/CHANGELOG.md
  check_config/build.json
  check_config/config.json
Labels: cla-signed

#1567 Update to Revision 112 of OpenZwave
  zwave/CHANGELOG.md
  zwave/build.json
  zwave/config.json
Labels: cla-signed

#1578 Add media folder support, bump alpine
  configurator/CHANGELOG.md
  configurator/Dockerfile
  configurator/build.json
  configurator/config.json
Labels: add-on: configurator, cla-signed

#1579 Add missing pip in Alpine 3.12
  configurator/Dockerfile
Labels: add-on: configurator, cla-signed

#1580 SSH: add bluetooth support & update cli
  ssh/CHANGELOG.md
  ssh/build.json
  ssh/config.json
Labels: cla-signed

#1581 zwave: fix vnc issues
  zwave/CHANGELOG.md
  zwave/Dockerfile
  zwave/build.json
  zwave/config.json
Labels: cla-signed

#1583 Roll back zwave add-on to 0.5.2
  zwave/config.json
Labels: cla-signed

#1573 Bump deCONZ to 2.05.81
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#1590 Mention zwave rollback in changelog
  zwave/CHANGELOG.md
Labels: cla-signed
