Repository home-assistant/addons, pull requests merged in 2020-07, with the labels that each got.

#1435 Update DOCS.md
  samba/DOCS.md
Labels: cla-signed

#1436 mariadb: Alpine 3.12, increase innodb_buffer_pool_size
  mariadb/CHANGELOG.md
  mariadb/build.json
  mariadb/config.json
  mariadb/rootfs/etc/my.cnf.d/mariadb-server.cnf
Labels: cla-signed

#1432 Bump deCONZ to 2.05.78
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#1441 letsencrypt: Fix DNS challenge provider format
  letsencrypt/DOCS.md
Labels: cla-signed

#1444 Update OpenZWave versions
  zwave/CHANGELOG.md
  zwave/Dockerfile
  zwave/build.json
  zwave/config.json
Labels: cla-signed

#1448 Cleanup jemalloc from mariadb because it's on base image now
  mariadb/Dockerfile
  mariadb/build.json
Labels: cla-signed

#1457 OpenZWave: Roll-back alpine, adjust open-zwave commit
  zwave/CHANGELOG.md
  zwave/build.json
  zwave/config.json
Labels: cla-signed

#1450 Don't delete the mariadb.sys yser
  mariadb/CHANGELOG.md
  mariadb/config.json
  mariadb/rootfs/etc/services.d/mariadb/run
Labels: add-on: mariadb, cla-signed

#1476 deconz: Refactor
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/build.json
  deconz/config.json
  deconz/data/discovery.sh
  deconz/data/ika-otau-dl.sh
  deconz/data/ledvance-otau-dl.sh
  deconz/rootfs/etc/cont-init.d/firmware.sh
  deconz/rootfs/etc/cont-init.d/nginx.sh
  deconz/rootfs/etc/cont-init.d/vnc.sh
  deconz/rootfs/etc/nginx/nginx.conf
  deconz/rootfs/etc/services.d/deconz/discovery
  deconz/rootfs/etc/services.d/deconz/finish
  deconz/rootfs/etc/services.d/deconz/run
  deconz/rootfs/etc/services.d/nginx/finish
  deconz/rootfs/etc/services.d/nginx/run
  deconz/rootfs/etc/services.d/otau-deconz/finish
  deconz/rootfs/etc/services.d/otau-deconz/run
  deconz/rootfs/etc/services.d/otau-ikea/finish
  deconz/rootfs/etc/services.d/otau-ikea/run
  deconz/rootfs/etc/services.d/otau-ledvance/finish
  deconz/rootfs/etc/services.d/otau-ledvance/run
  deconz/rootfs/etc/services.d/udev/finish
  deconz/rootfs/etc/services.d/udev/run
  deconz/rootfs/etc/services.d/udev/trigger
Labels: cla-signed

#1478 Fix wiringpi
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/config.json
Labels: cla-signed

#1479 Fix deCONZ armhf issues & wiringpi on aarch64
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#1483 deCONZ 6.1.1; Fix VNC on arm & Ledvance downloader
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/etc/services.d/deconz/run
  deconz/rootfs/etc/services.d/otau-ledvance/run
Labels: add-on: deconz, cla-signed

#1489 OpenZWave 0.5.2
  zwave/CHANGELOG.md
  zwave/Dockerfile
  zwave/build.json
  zwave/config.json
  zwave/rootfs/etc/cont-finish.d/mqtt.sh
  zwave/rootfs/etc/cont-init.d/mqtt.sh
  zwave/rootfs/etc/mosquitto.conf
  zwave/rootfs/etc/services.d/zwave/run
  zwave/rootfs/usr/lib/mqtt_helper.sh
Labels: cla-signed

#1504 check_config: Upgrade base image to 8.1.0
  check_config/CHANGELOG.md
  check_config/build.json
  check_config/config.json
Labels: cla-signed

#1491 Improve DNS-OVH documentation
  letsencrypt/DOCS.md
Labels: cla-signed

#1506 Cleanup zwave from remove ABI tags
  zwave/Dockerfile
Labels: cla-signed

#1505 Add novnc support deCONZ & rework ingress
  .devcontainer/start_supervisor.sh
  deconz/CHANGELOG.md
  deconz/DOCS.md
  deconz/Dockerfile
  deconz/config.json
  deconz/rootfs/etc/cont-init.d/novnc.sh
  deconz/rootfs/etc/cont-init.d/vnc.sh
  deconz/rootfs/etc/nginx/nginx.conf
  deconz/rootfs/etc/services.d/deconz/run
  deconz/rootfs/etc/services.d/otau-deconz/finish
  deconz/rootfs/etc/services.d/otau-ikea/finish
  deconz/rootfs/etc/services.d/otau-ledvance/finish
  deconz/rootfs/etc/services.d/udev/finish
  deconz/rootfs/etc/services.d/websockify/run
  deconz/rootfs/usr/share/www/ingress.html
Labels: cla-signed

#1513 Fix deCONZ issue with old vnc access
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/etc/services.d/deconz/run
Labels: cla-signed

#1518 Update IPv4/6 links (#1426)
  duckdns/DOCS.md
Labels: cla-signed

#1517 Update deCONZ ingress choose html styling
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/usr/share/www/ingress.html
Labels: cla-signed

#1520 Change email examples
  letsencrypt/DOCS.md
Labels: add-on: letsencrypt, cla-signed

#1523 Add background color to ingress deconz
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/usr/share/www/ingress.html
Labels: cla-signed
