Repository home-assistant/addons, pull requests merged in 2020-10, with the labels that each got.

#1608 Update DOCS.md
  letsencrypt/DOCS.md
Labels: cla-signed

#1605 Update DOCS.md
  almond/DOCS.md
Labels: cla-signed

#1606 Update DOCS.md
  dnsmasq/DOCS.md
Labels: cla-signed

#1607 Update DOCS.md
  google_assistant/DOCS.md
Labels: cla-signed

#1609 Update DOCS.md
  mosquitto/DOCS.md
Labels: cla-signed

#1610 letsencrypt: Add Njalla DNS support
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/Dockerfile
  letsencrypt/build.json
  letsencrypt/config.json
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed

#1616 Bump deCONZ to 2.05.84
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: Hacktoberfest, add-on: deconz, cla-signed

#1625 Update README.md
  README.md
Labels: cla-signed

#1627 🔨Ignore DB files on copy for check_config
  check_config/CHANGELOG.md
  check_config/Dockerfile
  check_config/config.json
  check_config/rootfs/etc/services.d/check-config/run
Labels: cla-signed

#1621 Enable autoscale for DeCONZ noVNC
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/usr/share/www/ingress.html
Labels: cla-signed

#1635 Add action to build changed add-ons
  .github/workflows/build.yml
Labels: cla-signed

#1637 Renames the build action
  .github/workflows/build.yml
Labels: cla-signed

#1646 Move from azure pipelines to github action for CI
  .devcontainer/start_supervisor.sh
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/builder.yml
  .github/workflows/lint.yml
  .shellcheckrc
  README.md
  ada/azure-pipelines.yml
  almond/azure-pipelines.yml
  azure-pipelines.yml
  cec_scan/azure-pipelines.yml
  check_config/azure-pipelines.yml
  configurator/azure-pipelines.yml
  deconz/azure-pipelines.yml
  dhcp_server/azure-pipelines.yml
  dnsmasq/azure-pipelines.yml
  duckdns/azure-pipelines.yml
  git_pull/azure-pipelines.yml
  google_assistant/azure-pipelines.yml
  homematic/azure-pipelines.yml
  letsencrypt/azure-pipelines.yml
  mariadb/azure-pipelines.yml
  mosquitto/azure-pipelines.yml
  nginx_proxy/azure-pipelines.yml
  rpc_shutdown/azure-pipelines.yml
  samba/azure-pipelines.yml
  ssh/azure-pipelines.yml
  tellstick/azure-pipelines.yml
  zwave/azure-pipelines.yml
Labels: cla-signed

#1647 Fix add-on build
  .github/workflows/builder.yml
Labels: cla-signed

#1650 Add Connection section to samba docs
  samba/DOCS.md
Labels: add-on: samba, cla-signed

#1654 DuckDns script read config off ipv4 and ipv6 correctly
  duckdns/CHANGELOG.md
  duckdns/config.json
  duckdns/data/run.sh
Labels: cla-signed

#1659 Set blank ipv4 and ipv6 if config is unset.
  duckdns/CHANGELOG.md
  duckdns/config.json
  duckdns/data/run.sh
Labels: cla-signed

#1655 Limit add-on build
  .github/workflows/builder.yml
Labels: cla-signed
