Repository home-assistant/addons, pull requests merged in 2020-03, with the labels that each got.

#1153 Add support for new audo layer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .shellcheckrc
  .vscode/tasks.json
  ada/CHANGELOG.md
  ada/Dockerfile
  ada/config.json
  ada/data/run.sh
  ada/rootfs/etc/services.d/ada/finish
  ada/rootfs/etc/services.d/ada/run
  azure-pipelines.yml
  ssh/CHANGELOG.md
  ssh/Dockerfile
  ssh/config.json
  ssh/data/run.sh
  ssh/rootfs/etc/cont-init.d/keygen.sh
  ssh/rootfs/etc/cont-init.d/profile.sh
  ssh/rootfs/etc/cont-init.d/ssh.sh
  ssh/rootfs/etc/fix-attrs.d/cli
  ssh/rootfs/etc/fix-attrs.d/profile
  ssh/rootfs/etc/fix-attrs.d/ssh
  ssh/rootfs/etc/motd
  ssh/rootfs/etc/profile.d/homeassistant.sh
  ssh/rootfs/etc/services.d/sshd/finish
  ssh/rootfs/etc/services.d/sshd/run
  ssh/rootfs/etc/services.d/ttyd/finish
  ssh/rootfs/etc/services.d/ttyd/run
  ssh/rootfs/etc/ssh/sshd_config
  ssh/rootfs/root/.tmux.conf
  ssh/rootfs/usr/bin/hassio
Labels: cla-signed

#1156 Show information/warning if the SSH port is disable
  ssh/CHANGELOG.md
  ssh/config.json
  ssh/rootfs/etc/services.d/sshd/run
Labels: cla-signed

#1160 Migrate google assistant to new audio
  .devcontainer/Dockerfile
  google_assistant/CHANGELOG.md
  google_assistant/Dockerfile
  google_assistant/build.json
  google_assistant/config.json
  google_assistant/rootfs/etc/services.d/google-assistant/finish
  google_assistant/rootfs/etc/services.d/google-assistant/run
  google_assistant/rootfs/usr/bin/hassio_gassistant.py
  google_assistant/rootfs/usr/bin/hassio_oauth.py
Labels: cla-signed

#1148 Fix certificate request logic
  letsencrypt/data/run.sh
Labels: add-on: letsencrypt, cla-signed

#1162 More information about port to SSH README.md
  ssh/README.md
Labels: add-on: ssh, cla-signed

#1154 Add information on README.md
  mosquitto/README.md
Labels: cla-signed

#1167 Update Home Assistant CLI to 4.1.0
  git_pull/CHANGELOG.md
  git_pull/build.json
  git_pull/config.json
  ssh/CHANGELOG.md
  ssh/build.json
  ssh/config.json
Labels: cla-signed

#1168 Fix Google Assistant armhf/armv7
  google_assistant/CHANGELOG.md
  google_assistant/Dockerfile
  google_assistant/azure-pipelines.yml
  google_assistant/config.json
  google_assistant/rootfs/etc/services.d/google-assistant/run
Labels: cla-signed

#1169 Wait a bit longer until udev is finish
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/data/run.sh
Labels: cla-signed

#1177 deconz: Bump deCONZ to 2.05.75
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: add-on: deconz, cla-signed

#1182 Fix steps for adding integration
  mosquitto/README.md
Labels: add-on: mosquitto, cla-signed

#1189 Fix typo in readme
  rpc_shutdown/README.md
Labels: cla-signed

#1178 Update Almond to 1.7.3
  almond/build.json
  almond/config.json
Labels: cla-signed

#1166 Fix certificate request logic & S6-Overlay
  azure-pipelines.yml
  letsencrypt/CHANGELOG.md
  letsencrypt/Dockerfile
  letsencrypt/config.json
  letsencrypt/data/run.sh
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/finish
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
  ssh/rootfs/etc/services.d/ttyd/run
Labels: cla-signed

#1196 ssh: Upgrade CLI to 4.2.0
  ssh/CHANGELOG.md
  ssh/build.json
  ssh/config.json
Labels: add-on: ssh, cla-signed

#1195 git_pull: Upgrade CLI to 4.2.0
  git_pull/CHANGELOG.md
  git_pull/build.json
  git_pull/config.json
Labels: add-on: git_pull, cla-signed

#1200 Jemalloc for mariadb
  .devcontainer/start_supervisor.sh
  .vscode/tasks.json
  mariadb/CHANGELOG.md
  mariadb/Dockerfile
  mariadb/build.json
  mariadb/config.json
  mariadb/rootfs/etc/my.cnf.d/mariadb-server.cnf
  mariadb/rootfs/etc/services.d/mariadb/finish
  mariadb/rootfs/etc/services.d/mariadb/run
Labels: cla-signed

#1198 changed "GOOGLE_SDK_VERSION" back to version "0.5.0"
  google_assistant/CHANGELOG.md
  google_assistant/build.json
  google_assistant/config.json
Labels: cla-signed

#1201 Fix config check add-on
  check_config/CHANGELOG.md
  check_config/Dockerfile
  check_config/build.json
  check_config/config.json
  check_config/rootfs/etc/services.d/config-checker/finish
  check_config/rootfs/etc/services.d/config-checker/run
Labels: cla-signed
