Repository home-assistant/addons, pull requests merged in 2020-06, with the labels that each got.

#1356 Add feedback_sound option [add-on: google_assistant]
  google_assistant/CHANGELOG.md
  google_assistant/DOCS.md
  google_assistant/Dockerfile
  google_assistant/config.json
  google_assistant/rootfs/etc/services.d/google-assistant/run
  google_assistant/rootfs/usr/bin/hassio_gassistant.py
  google_assistant/rootfs/usr/share/sounds/end_sound.wav
  google_assistant/rootfs/usr/share/sounds/start_sound.wav
Labels: add-on: google_assistant, cla-signed

#1365 duckdns: Fix missing example options in documentation
  duckdns/DOCS.md
Labels: cla-signed

#1364 SSH: Add local TCP forwarding option
  ssh/CHANGELOG.md
  ssh/DOCS.md
  ssh/config.json
  ssh/rootfs/etc/cont-init.d/ssh.sh
Labels: cla-signed

#1375 Downgraded deCONZ to 2.05.75
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#1380 zwave: Add instance config
  zwave/DOCS.md
  zwave/config.json
  zwave/rootfs/etc/services.d/zwave/run
Labels: cla-signed

#1396 Update link
  README.md
Labels: cla-signed

#1381 letsencrypt: Add DirectAdmin DNS provider
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/Dockerfile
  letsencrypt/build.json
  letsencrypt/config.json
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed

#1397 Fix optional instance parameter
  zwave/CHANGELOG.md
  zwave/config.json
Labels: add-on: zwave, cla-signed

#1400 Improve error message when using documented network_key
  zwave/CHANGELOG.md
  zwave/config.json
  zwave/rootfs/etc/cont-init.d/network_key.sh
Labels: cla-signed

#1399 zwave: Update Open-ZWave version
  zwave/CHANGELOG.md
  zwave/build.json
  zwave/config.json
Labels: cla-signed

#1383 letsencrypt: Add custom ACME server option
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/config.json
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed

#1413 zwave: Update Open-ZWave version
  zwave/CHANGELOG.md
  zwave/build.json
  zwave/config.json
Labels: cla-signed

#1422 duckdns: clean up lock file at start also if no live cert exists
  duckdns/CHANGELOG.md
  duckdns/config.json
  duckdns/data/run.sh
Labels: cla-signed
