Repository home-assistant/addons, pull requests merged in 2020-11, with the labels that each got.

#1664 DNSmasq documentation update to use alongside AdGuard addon
  dnsmasq/DOCS.md
Labels: cla-signed

#1594 Clarify that remote SSH access is disabled by default and expand upon…
  ssh/DOCS.md
Labels: add-on: ssh, cla-signed, in progress

#1670 Document how to enable the option to add a new user
  mosquitto/DOCS.md
Labels: add-on: mosquitto, cla-signed

#1667 Add HTTP configuration instructions to DuckDNS documentation
  duckdns/DOCS.md
Labels: add-on: duckdns, cla-signed

#1669 Allow Configurator to skip git initialization
  configurator/CHANGELOG.md
  configurator/DOCS.md
  configurator/config.json
  configurator/rootfs/etc/services.d/configurator/run
Labels: add-on: configurator, cla-signed

#1652 Clarify where to store the mosquitto certificate files
  mosquitto/DOCS.md
Labels: cla-signed, hacktoberfest-accepted

#1676 deCONZ 2.5.87 (stable)
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#1686 November update for OZW
  zwave/CHANGELOG.md
  zwave/Dockerfile
  zwave/build.json
  zwave/config.json
Labels: add-on: zwave, cla-signed

#1687 Simplify devcontainer setup
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/supervisor.sh
  .vscode/tasks.json
Labels: cla-signed

#1691 Fix ozw timezone alpine issue
  zwave/CHANGELOG.md
  zwave/config.json
Labels: cla-signed

#1692 ssh: Upgrades Home Assistant CLI to v4.9.0
  ssh/CHANGELOG.md
  ssh/build.json
  ssh/config.json
Labels: cla-signed

#1695 Include link to mosquitto documentation
  mosquitto/README.md
Labels: add-on: mosquitto, cla-signed

#1697 Fix typo in mosquitto
  mosquitto/README.md
Labels: cla-signed
