Repository home-assistant/addons, pull requests merged in 2020-02, with the labels that each got.

#1031 google_assistant: Corrects broken link
  google_assistant/README.md
Labels: add-on: google_assistant, cla-signed

#1037 Update almond 1.7.2
  almond/CHANGELOG.md
  almond/build.json
  almond/config.json
Labels: cla-signed

#1038 ssh: Fix new tmux windows, add add-on icon
  ssh/CHANGELOG.md
  ssh/data/.tmux.conf
  ssh/icon.png
Labels: add-on: ssh, cla-signed

#1039 Ssh update
  ssh/CHANGELOG.md
  ssh/config.json
  ssh/data/.tmux.conf
  ssh/data/motd
  ssh/data/run.sh
  ssh/icon.png
Labels: cla-signed

#1045 Add icons & logos to all add-ons
  ada/icon.png
  ada/logo.png
  almond/icon.png
  cec_scan/icon.png
  cec_scan/logo.png
  check_config/icon.png
  check_config/logo.png
  configurator/icon.png
  configurator/logo.png
  deconz/icon.png
  dhcp_server/icon.png
  dnsmasq/icon.png
  duckdns/icon.png
  git_pull/icon.png
  google_assistant/icon.png
  homematic/icon.png
  letsencrypt/icon.png
  letsencrypt/logo.png
  mariadb/icon.png
  mosquitto/icon.png
  nginx_proxy/icon.png
  rpc_shutdown/icon.png
  rpc_shutdown/logo.png
  samba/icon.png
  tellstick/icon.png
Labels: cla-signed

#1044 snips: Remove add-on from repository
  README.md
  snips/CHANGELOG.md
  snips/Dockerfile
  snips/README.md
  snips/azure-pipelines.yml
  snips/build.json
  snips/config.json
  snips/data/customtts.sh
  snips/data/mosquitto.conf
  snips/data/run.sh
  snips/data/snips-entrypoint.sh
Labels: add-on: snips, cla-signed

#1040 Add devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/start_hassio.sh
  .vscode/tasks.json
Labels: cla-signed

#1046 Re-branding of core add-ons
  README.md
  ada/README.md
  ada/config.json
  almond/README.md
  cec_scan/README.md
  check_config/README.md
  configurator/README.md
  deconz/README.md
  deconz/config.json
  deconz/data/run.sh
  dhcp_server/README.md
  dnsmasq/README.md
  duckdns/README.md
  git_pull/Dockerfile
  git_pull/README.md
  google_assistant/README.md
  google_assistant/data/hassio_gassistant.py
  google_assistant/data/run.sh
  homematic/README.md
  letsencrypt/README.md
  mariadb/README.md
  mosquitto/README.md
  mosquitto/data/run.sh
  nginx_proxy/README.md
  rpc_shutdown/README.md
  samba/README.md
  samba/config.json
  ssh/Dockerfile
  ssh/README.md
  ssh/config.json
  ssh/data/run.sh
  tellstick/README.md
Labels: cla-signed

#1047 Re-branding and updating for latest supervisor
  ada/README.md
  almond/README.md
  cec_scan/README.md
  check_config/README.md
  configurator/README.md
  deconz/README.md
  dhcp_server/README.md
  dnsmasq/README.md
  duckdns/README.md
  git_pull/README.md
  google_assistant/README.md
  homematic/README.md
  letsencrypt/README.md
  mariadb/README.md
  mosquitto/README.md
  nginx_proxy/README.md
  rpc_shutdown/README.md
  samba/README.md
  ssh/README.md
  tellstick/README.md
Labels: cla-signed

#1050 Support more CEC types
  cec_scan/CHANGELOG.md
  cec_scan/Dockerfile
  cec_scan/config.json
  cec_scan/data/libcec.patch
Labels: cla-signed

#1030 added support for netcup dns
  letsencrypt/CHANGELOG.md
  letsencrypt/Dockerfile
  letsencrypt/README.md
  letsencrypt/build.json
  letsencrypt/config.json
  letsencrypt/data/run.sh
Labels: cla-signed

#1052 Allow global usage of CEC
  cec_scan/CHANGELOG.md
  cec_scan/README.md
  cec_scan/config.json
Labels: cla-signed

#1059 Spell check
  almond/data/run.sh
Labels: cla-signed

#1061 HomeMatic fix issue with glibc
  homematic/CHANGELOG.md
  homematic/build.json
  homematic/config.json
Labels: cla-signed

#1065 remove lastboot before supervisor startup
  .devcontainer/Dockerfile
  .devcontainer/start_hassio.sh
Labels: cla-signed

#1068 ssh: Update CLI & Web terminal
  ssh/CHANGELOG.md
  ssh/Dockerfile
  ssh/build.json
  ssh/config.json
  ssh/data/hassio
  ssh/data/homeassistant.sh
  ssh/data/motd
  ssh/data/run.sh
Labels: add-on: ssh, cla-signed

#1072 Update homematic OCCU 3.51.6
  homematic/CHANGELOG.md
  homematic/Dockerfile
  homematic/build.json
  homematic/config.json
Labels: cla-signed

#1073 Allow api token for cloudflare
  letsencrypt/CHANGELOG.md
  letsencrypt/README.md
  letsencrypt/build.json
  letsencrypt/config.json
  letsencrypt/data/run.sh
Labels: cla-signed

#1074 Use wheels for LE
  letsencrypt/Dockerfile
Labels: cla-signed

#1067 Rewrite MariaDB add-on
  mariadb/CHANGELOG.md
  mariadb/Dockerfile
  mariadb/README.md
  mariadb/build.json
  mariadb/config.json
  mariadb/data/mariadb-server.cnf
  mariadb/data/run.sh
Labels: add-on: mariadb, cla-signed

#1075 Update README.md
  mariadb/README.md
Labels: add-on: mariadb, cla-signed

#1079 Optimize Homematic jobs
  homematic/CHANGELOG.md
  homematic/build.json
  homematic/config.json
  homematic/data/run.sh
Labels: cla-signed

#1083 Support aarch64 with armv7 in combat
  ada/CHANGELOG.md
  ada/build.json
  ada/config.json
Labels: cla-signed

#1084 Ingress for Homematic
  homematic/CHANGELOG.md
  homematic/Dockerfile
  homematic/build.json
  homematic/config.json
  homematic/data/nginx.conf
  homematic/data/run.sh
Labels: cla-signed

#1085 Fix proto with SSL
  homematic/CHANGELOG.md
  homematic/config.json
  homematic/data/nginx.conf
Labels: cla-signed

#1088 Bump deCONZ to 2.05.73
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/data/nginx.conf
Labels: add-on: deconz, cla-signed

#1089 configurator: Name change to File editor
  configurator/CHANGELOG.md
  configurator/config.json
Labels: add-on: configurator, cla-signed

#1090 Update configurator to 0.3.8
  configurator/CHANGELOG.md
  configurator/build.json
  configurator/config.json
Labels: add-on: configurator, cla-signed

#1091 Update README.md
  configurator/README.md
Labels: add-on: configurator, cla-signed

#1094 Reverts file editor 4.4 release changes
  configurator/CHANGELOG.md
  configurator/build.json
  configurator/config.json
Labels: add-on: configurator, cla-signed

#1099 cloudflare selected and streamline propagation seconds
  letsencrypt/CHANGELOG.md
  letsencrypt/README.md
  letsencrypt/config.json
  letsencrypt/data/run.sh
Labels: cla-signed

#1101 Update README.md
  README.md
Labels: cla-signed

#1100 Update configurator to 0.3.9
  configurator/CHANGELOG.md
  configurator/build.json
  configurator/config.json
Labels: add-on: configurator, cla-signed

#1103 Fix missing variable DNS
  letsencrypt/CHANGELOG.md
  letsencrypt/config.json
  letsencrypt/data/run.sh
Labels: cla-signed

#1108 Add flags for stage and advanced
  dhcp_server/config.json
  dnsmasq/config.json
  git_pull/config.json
  google_assistant/config.json
Labels: cla-signed

#1109 Migrate GitPull new CLI
  git_pull/CHANGELOG.md
  git_pull/Dockerfile
  git_pull/build.json
  git_pull/config.json
  git_pull/data/run.sh
Labels: cla-signed

#1115 Update configuration example
  samba/README.md
Labels: add-on: samba, cla-signed

#1117 Support to use SSH as webterminal only
  ssh/CHANGELOG.md
  ssh/README.md
  ssh/config.json
  ssh/data/run.sh
Labels: cla-signed

#1120 [letsencrypt] Fixing cloudflare configuration parameters in the readme
  letsencrypt/README.md
Labels: cla-signed

#1121 Pretty output homematic
  homematic/CHANGELOG.md
  homematic/config.json
  homematic/data/run.sh
Labels: cla-signed

#1122 Extend regahss for homematic
  homematic/CHANGELOG.md
  homematic/README.md
  homematic/config.json
  homematic/data/run.sh
Labels: cla-signed

#1077 duckdns: add option to grab IP addresses from URLs
  duckdns/CHANGELOG.md
  duckdns/README.md
  duckdns/config.json
  duckdns/data/run.sh
Labels: cla-signed

#1082 Update nginx.conf
  nginx_proxy/CHANGELOG.md
  nginx_proxy/build.json
  nginx_proxy/config.json
  nginx_proxy/data/nginx.conf
  nginx_proxy/data/run.sh
Labels: cla-signed

#1132 Update configurator to 4.7
  configurator/CHANGELOG.md
  configurator/build.json
  configurator/config.json
Labels: add-on: configurator, cla-signed

#1131 Adjust readme to point to new name 'Supervisor'
  deconz/README.md
Labels: cla-signed

#1136 Update README.md
  configurator/README.md
Labels: add-on: configurator, cla-signed

#1127 mosquitto: Add missing login configuration details
  mosquitto/README.md
Labels: add-on: mosquitto, cla-signed

#1140 deconz: Bump deCONZ to 2.05.74
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#1138 Add link to Almond homepage in README
  almond/README.md
Labels: cla-signed

#1146 deconz: update hostname in VNC URL example
  deconz/README.md
Labels: add-on: deconz, cla-signed
