Repository home-assistant/addons, pull requests merged in 2021-12, with the labels that each got.

#2297 Bump zwave-js to 8.8.3
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#2312 deCONZ 2.13.4 (stable)
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/build.yaml
  deconz/config.yaml
Labels: cla-signed

#2318 Revert "deCONZ 2.13.4 (stable)"
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/build.yaml
  deconz/config.yaml
Labels: cla-signed

#2319 deCONZ 2.13.04, add-on version 6.11.1
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/build.yaml
  deconz/config.yaml
Labels: cla-signed, add-on: deconz

#2307 Allow use of ports other than 8123 in HA
  nginx_proxy/CHANGELOG.md
  nginx_proxy/config.yaml
  nginx_proxy/data/nginx.conf
  nginx_proxy/data/run.sh
Labels: cla-signed, add-on: nginx_proxy

#2310 Fixed bash PS1 escaping
  ssh/CHANGELOG.md
  ssh/config.yaml
  ssh/rootfs/usr/share/tempio/homeassistant.profile
Labels: cla-signed, add-on: ssh

#2327 Bump zwave-js to 8.9.2 and zwave-js-server to 1.14.0
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed
