Repository home-assistant/addons, pull requests merged in 2021-08, with the labels that each got.

#2138 git_pull: Typo in log message
  git_pull/data/run.sh
Labels: cla-signed, add-on: git_pull

#2148 Bump zwave-js to 8.1.1
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#2149 Bump zwave-js-server to 1.10.0
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#2150 deCONZ 2.12.6 (stable)
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#2154 Updated documentation for Raspberry Pi 3/4 setup
  homematic/DOCS.md
Labels: cla-signed, add-on: homematic

#2156 Mark zwave_js as stable
  zwave_js/config.json
Labels: cla-signed
