Repository home-assistant/addons, pull requests merged in 2021-06, with the labels that each got.

#2062 Avoid propagation of error status on clean shutdown
  mariadb/rootfs/etc/services.d/mariadb/run
Labels: add-on: mariadb, cla-signed

#2065 Bump zwave-js to 7.7.3
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#2070 Samba: Add hassio_api to add-on configuration
  samba/CHANGELOG.md
  samba/config.json
Labels: add-on: samba, cla-signed

#2075 Bump zwave-js to 7.7.4
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#2063 Add lock capabilities during snapshot
  mariadb/CHANGELOG.md
  mariadb/config.json
  mariadb/rootfs/etc/services.d/mariadb-lock/down
  mariadb/rootfs/etc/services.d/mariadb-lock/finish
  mariadb/rootfs/etc/services.d/mariadb-lock/notification-fd
  mariadb/rootfs/etc/services.d/mariadb-lock/run
Labels: add-on: mariadb, cla-signed

#2083 Store deconz persistent
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/etc/cont-init.d/deconz.sh
Labels: add-on: deconz, cla-signed

#2084 Revert "Store deconz persistent"
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/etc/cont-init.d/firmware.sh
Labels: cla-signed

#2077 Incorporated new required proxy settings to nginx docs
  nginx_proxy/DOCS.md
Labels: cla-signed

#2090 Bump zwave-js to 7.9.0
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#2096 Bump zwave-js and zwave-js-server
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#2099 Update duckdns URLs
  duckdns/DOCS.md
  duckdns/README.md
Labels: add-on: duckdns, cla-signed
