Repository home-assistant/addons, pull requests merged in 2021-02, with the labels that each got.

#1794 Bump zwave_js server to 1.0.0-beta.2
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1798 Fix deconz error spam with supervisor beta
  .devcontainer/supervisor.sh
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/etc/services.d/udev/run
Labels: cla-signed

#1799 Bump Z-Wave JS Server to 1.0.0-beta.3
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1800 SSH: Use new banner and tempio
  ssh/CHANGELOG.md
  ssh/Dockerfile
  ssh/build.json
  ssh/config.json
  ssh/rootfs/etc/cont-init.d/keygen.sh
  ssh/rootfs/etc/cont-init.d/profile.sh
  ssh/rootfs/etc/cont-init.d/ssh.sh
  ssh/rootfs/etc/motd
  ssh/rootfs/etc/profile.d/homeassistant.sh
  ssh/rootfs/etc/services.d/sshd/run
  ssh/rootfs/root/.bash_history
  ssh/rootfs/root/.bash_profile
  ssh/rootfs/root/.ssh
  ssh/rootfs/usr/share/tempio/homeassistant.profile
  ssh/rootfs/usr/share/tempio/sshd_config
Labels: cla-signed

#1803 Corrected version in changelog for ssh & terminal addon
  ssh/CHANGELOG.md
Labels: add-on: ssh, cla-signed

#1806 Bump zwavejs server to 1.0.0-beta.4
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1810 ssh: Upgrade CLI to 4.10.1
  ssh/CHANGELOG.md
  ssh/build.json
  ssh/config.json
Labels: add-on: ssh, cla-signed

#1825 Fix config style for new Supervisor/Hardware
  ada/config.json
  almond/config.json
  configurator/config.json
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/etc/services.d/deconz/run
  deconz/rootfs/etc/services.d/udev/run
  deconz/rootfs/etc/services.d/udev/trigger
  dhcp_server/config.json
  dnsmasq/config.json
  duckdns/config.json
  google_assistant/config.json
  homematic/CHANGELOG.md
  homematic/config.json
  mariadb/config.json
  mosquitto/config.json
  nginx_proxy/config.json
  rpc_shutdown/config.json
  samba/config.json
  ssh/config.json
  tellstick/CHANGELOG.md
  tellstick/Dockerfile
  tellstick/build.json
  tellstick/config.json
  zwave/CHANGELOG.md
  zwave/config.json
  zwave_js/CHANGELOG.md
  zwave_js/config.json
Labels: cla-signed

#1813 Add some clarity to Z-Wave JS add-on documentation
  zwave_js/DOCS.md
Labels: cla-signed

#1708 mosquitto: Set mosquitto.conf log_type based on logging level
  mosquitto/data/auth_srv.sh
  mosquitto/data/mosquitto.conf
  mosquitto/data/run.sh
Labels: add-on: mosquitto, cla-signed

#1785 🐛 Fix problems with alias domains and dns-01 challenge
  duckdns/CHANGELOG.md
  duckdns/DOCS.md
  duckdns/config.json
  duckdns/data/run.sh
Labels: cla-signed

#1832 Fix duckdns json
  duckdns/config.json
Labels: cla-signed

#1831 Hm 3.55.10
  homematic/CHANGELOG.md
  homematic/DOCS.md
  homematic/build.json
  homematic/config.json
Labels: cla-signed

#1830 Specific install zwave js
  zwave_js/CHANGELOG.md
  zwave_js/Dockerfile
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1836 Update zwave-js to 6.2.0 release
  zwave_js/CHANGELOG.md
  zwave_js/build.json
Labels: cla-signed

#1837 Bump zwave_js to 0.1.6
  zwave_js/config.json
Labels: add-on: zwave_js, cla-signed

#1841 deCONZ 2.9.3 (stable)
  deconz/CHANGELOG.md
  deconz/build.json
  deconz/config.json
Labels: cla-signed

#1845 tellstick: Improve logo and icon
  tellstick/icon.png
  tellstick/logo.png
Labels: add-on: tellstick, cla-signed

#1846 nginx: make transparent logo
  nginx_proxy/logo.png
Labels: add-on: nginx_proxy, cla-signed

#1824 Support srv-host records
  dnsmasq/CHANGELOG.md
  dnsmasq/DOCS.md
  dnsmasq/apparmor.txt
  dnsmasq/config.json
  dnsmasq/data/run.sh
  dnsmasq/rootfs/usr/share/tempio/dnsmasq.config
Labels: cla-signed

#1851 Revert "Support srv-host records"
  dnsmasq/CHANGELOG.md
  dnsmasq/DOCS.md
  dnsmasq/apparmor.txt
  dnsmasq/config.json
  dnsmasq/data/run.sh
  dnsmasq/rootfs/usr/share/tempio/dnsmasq.config
Labels: cla-signed

#1852 Bump zwave-js-server to 1.0.0-beta.6
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1853 Support svr host
  dnsmasq/CHANGELOG.md
  dnsmasq/DOCS.md
  dnsmasq/Dockerfile
  dnsmasq/apparmor.txt
  dnsmasq/build.json
  dnsmasq/config.json
  dnsmasq/data/dnsmasq.conf
  dnsmasq/data/run.sh
  dnsmasq/rootfs/etc/cont-init.d/config.sh
  dnsmasq/rootfs/etc/services.d/dnsmasq/finish
  dnsmasq/rootfs/etc/services.d/dnsmasq/run
  dnsmasq/rootfs/usr/share/tempio/dnsmasq.config
Labels: cla-signed

#1860 Revert "Support svr host (#1853)"
  dnsmasq/CHANGELOG.md
  dnsmasq/DOCS.md
  dnsmasq/Dockerfile
  dnsmasq/apparmor.txt
  dnsmasq/build.json
  dnsmasq/config.json
  dnsmasq/data/dnsmasq.conf
  dnsmasq/data/run.sh
  dnsmasq/rootfs/etc/cont-init.d/config.sh
  dnsmasq/rootfs/etc/services.d/dnsmasq/finish
  dnsmasq/rootfs/etc/services.d/dnsmasq/run
  dnsmasq/rootfs/usr/share/tempio/dnsmasq.config
Labels: cla-signed

#1863 Support svr host
  dnsmasq/CHANGELOG.md
  dnsmasq/DOCS.md
  dnsmasq/Dockerfile
  dnsmasq/apparmor.txt
  dnsmasq/build.json
  dnsmasq/config.json
  dnsmasq/data/dnsmasq.conf
  dnsmasq/data/run.sh
  dnsmasq/rootfs/etc/cont-init.d/config.sh
  dnsmasq/rootfs/etc/services.d/dnsmasq/finish
  dnsmasq/rootfs/etc/services.d/dnsmasq/run
  dnsmasq/rootfs/usr/share/tempio/dnsmasq.config
Labels: cla-signed

#1862 Add VLC add-on
  vlc/CHANGELOG.md
  vlc/DOCS.md
  vlc/Dockerfile
  vlc/README.md
  vlc/build.json
  vlc/config.json
  vlc/icon.png
  vlc/logo.png
  vlc/rootfs/etc/cont-init.d/ingress.sh
  vlc/rootfs/etc/cont-init.d/secret.sh
  vlc/rootfs/etc/services.d/nginx/finish
  vlc/rootfs/etc/services.d/nginx/run
  vlc/rootfs/etc/services.d/vlc/discovery
  vlc/rootfs/etc/services.d/vlc/finish
  vlc/rootfs/etc/services.d/vlc/run
  vlc/rootfs/usr/share/tempio/nginx.conf
Labels: cla-signed

#1864 dnsmasq apparmor tweeks
  dnsmasq/CHANGELOG.md
  dnsmasq/apparmor.txt
  dnsmasq/config.json
Labels: cla-signed

#1867 Restart nginx for ingress on error
  almond/CHANGELOG.md
  almond/Dockerfile
  almond/build.json
  almond/config.json
  almond/rootfs/etc/services.d/nginx/finish
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/etc/services.d/nginx/finish
  homematic/CHANGELOG.md
  homematic/config.json
  homematic/rootfs/etc/services.d/nginx/finish
  vlc/CHANGELOG.md
  vlc/config.json
  vlc/rootfs/etc/services.d/nginx/finish
Labels: cla-signed

#1870 Fix issue with Almond packages
  almond/CHANGELOG.md
  almond/Dockerfile
  almond/config.json
Labels: cla-signed

#1871 Revert nginx change
  almond/CHANGELOG.md
  almond/config.json
  almond/rootfs/etc/services.d/nginx/finish
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/etc/services.d/nginx/finish
  homematic/CHANGELOG.md
  homematic/config.json
  homematic/rootfs/etc/services.d/nginx/finish
  vlc/CHANGELOG.md
  vlc/config.json
  vlc/rootfs/etc/services.d/nginx/finish
Labels: cla-signed

#1875 Deconz - cleanup old options
  deconz/CHANGELOG.md
  deconz/config.json
Labels: cla-signed

#1876 Fix version of HomeMatic
  homematic/config.json
Labels: cla-signed

#1879 Bump Z-Wave JS add-on to 0.1.8
  zwave_js/CHANGELOG.md
  zwave_js/Dockerfile
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1883 Fix password schema
  git_pull/CHANGELOG.md
  git_pull/config.json
  mariadb/CHANGELOG.md
  mariadb/config.json
  mosquitto/CHANGELOG.md
  mosquitto/config.json
  samba/CHANGELOG.md
  samba/config.json
  ssh/CHANGELOG.md
  ssh/config.json
Labels: cla-signed

#1884 Z-Wave JS: Bump ZJS Server to 2.0.0
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1885 Bump ZJS Server to 1.1.0
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed
