Repository home-assistant/addons, pull requests merged in 2021-04, with the labels that each got.

#1951 Bump zwave-js-server to 1.3.1
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1941 Added privilege control per user/db to MariaDB
  mariadb/DOCS.md
  mariadb/config.json
  mariadb/rootfs/etc/services.d/mariadb/run
Labels: cla-signed

#1959 Added changelog and version for privilege option
  mariadb/CHANGELOG.md
  mariadb/config.json
Labels: cla-signed

#1961 Bump zwave_js addon dependency versions
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1970 Bump zwave-js to 7.2.2
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1950 Expose log level as a configuration option for zwave_js
  zwave_js/DOCS.md
  zwave_js/config.json
  zwave_js/rootfs/etc/cont-init.d/config.sh
  zwave_js/rootfs/usr/share/tempio/zwave_config.conf
Labels: cla-signed

#1974 Bump zwave-js node pkg and addon version
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1980 Bump zwave-js-server to 1.5.0 and zwave-js to 7.2.4
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1985 Update configurator / file editor to 0.4.1
  configurator/CHANGELOG.md
  configurator/build.json
  configurator/config.json
Labels: cla-signed

#1975 Check Config 3.7.0
  check_config/CHANGELOG.md
  check_config/build.json
  check_config/config.json
  check_config/rootfs/etc/services.d/check-config/finish
  check_config/rootfs/etc/services.d/check-config/run
Labels: add-on: check_config, cla-signed

#1972 Make mariadb logo transparent
  mariadb/logo.png
Labels: cla-signed

#1988 Fix issues on WSL2
  .devcontainer/Dockerfile
Labels: cla-signed

#1991 git_pull: Bump CLI & Base image
  git_pull/CHANGELOG.md
  git_pull/build.json
  git_pull/config.json
  git_pull/data/run.sh
Labels: add-on: git_pull, cla-signed

#1992 Fix wsl2
  .devcontainer/Dockerfile
  .devcontainer/supervisor.sh
Labels: cla-signed

#1990 ssh: Upgrade Home Assistant CLI
  ssh/CHANGELOG.md
  ssh/Dockerfile
  ssh/build.json
  ssh/config.json
Labels: add-on: ssh, cla-signed

#1989 check_config: Upgrades add-on base image to 2021.04.3
  check_config/CHANGELOG.md
  check_config/build.json
  check_config/config.json
Labels: add-on: check_config, cla-signed
