Repository home-assistant/addons, pull requests merged in 2021-01, with the labels that each got.

#1741 docs: clarify Google add-on versus integration
  google_assistant/README.md
Labels: add-on: google_assistant, cla-signed

#1744 homematic: backup groups
  homematic/CHANGELOG.md
  homematic/config.json
  homematic/rootfs/etc/cont-init.d/env.sh
Labels: cla-error, cla-signed

#1748 Zwave: update ozw 66619ed
  zwave/CHANGELOG.md
  zwave/build.json
  zwave/config.json
Labels: cla-signed

#1750 HomeMatic: Migrate OCCU back to eq-3
  homematic/CHANGELOG.md
  homematic/Dockerfile
  homematic/build.json
  homematic/rootfs/etc/cont-finish.d/regahss.sh
  homematic/rootfs/etc/cont-init.d/env.sh
  homematic/rootfs/etc/cont-init.d/hm_rfd.sh
  homematic/rootfs/etc/cont-init.d/hm_wired.sh
  homematic/rootfs/etc/services.d/lighttpd/run
  homematic/rootfs/etc/services.d/regahss/run
  homematic/rootfs/etc/services.d/rfd/run
  homematic/rootfs/etc/services.d/timesync/run
  homematic/rootfs/etc/services.d/wired/run
Labels: cla-signed

#1752 Fix typo in deconz documentation
  deconz/DOCS.md
Labels: add-on: deconz, cla-signed

#1757 *: spelling fixes
  deconz/rootfs/etc/services.d/deconz/run
  mariadb/rootfs/etc/services.d/mariadb/run
  samba/DOCS.md
  zwave/CHANGELOG.md
Labels: cla-signed

#1756 homematic: fix rega.conf delete during build
  homematic/Dockerfile
Labels: cla-signed

#1753 Add warning about loss if run with an empty repo
  git_pull/DOCS.md
Labels: add-on: git_pull, cla-signed

#1776 Use ${MARIADB_DATA} everywhere in run script
  mariadb/rootfs/etc/services.d/mariadb/run
Labels: add-on: mariadb

#1780 Fix and clean zwave_js add-on
  zwave_js/Dockerfile
  zwave_js/config.json
  zwave_js/rootfs/etc/cont-init.d/config.sh
  zwave_js/rootfs/usr/share/tempio/zwave_config.json
Labels: cla-signed

#1766 Add initial support for ZWave JS
  zwave/CHANGELOG.md
  zwave/build.json
  zwave/config.json
  zwave_js/CHANGELOG.md
  zwave_js/DOCS.md
  zwave_js/Dockerfile
  zwave_js/README.md
  zwave_js/build.json
  zwave_js/config.json
  zwave_js/icon.png
  zwave_js/logo.png
  zwave_js/rootfs/etc/cont-init.d/config.sh
  zwave_js/rootfs/etc/cont-init.d/structure.sh
  zwave_js/rootfs/etc/services.d/zwave_js/discovery
  zwave_js/rootfs/etc/services.d/zwave_js/finish
  zwave_js/rootfs/etc/services.d/zwave_js/run
  zwave_js/rootfs/usr/share/tempio/zwave_config.conf
Labels: cla-signed

#1781 Validate network-key zwave-js
  zwave_js/config.json
Labels: cla-signed

#1782 Bump server version of zwave_js addon to 1.0.0-beta.1
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#1786 Change version requirement to 2021.2.0b0
  zwave_js/config.json
Labels: cla-signed

#1789 Use hostname for deconz discovery host instead of IP
  deconz/CHANGELOG.md
  deconz/config.json
  deconz/rootfs/etc/services.d/deconz/discovery
Labels: add-on: deconz, cla-signed
