Repository home-assistant/addons, pull requests merged in 2021-09, with the labels that each got.

#2088 Rename snapshot -> backup
  deconz/config.json
  mariadb/config.json
  mariadb/rootfs/etc/services.d/mariadb-lock/run
  samba/DOCS.md
Labels: cla-signed, add-on: deconz, add-on: mariadb

#2159 Bump zwave-js to 8.2.1 and zwave-js-server to 1.10.3
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed, add-on: zwave_js

#2176 Bump zwave-js to 8.2.3
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#2178 Bump zwave-js to 8.3.0
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#2190 Make SSH promt a bit color full
  ssh/CHANGELOG.md
  ssh/build.json
  ssh/rootfs/usr/share/tempio/homeassistant.profile
Labels: cla-signed

#2193 Use action for stale bot
  .github/stale.yml
  .github/workflows/stale.yml
Labels: cla-signed

#2192 Update check config add-on
  check_config/CHANGELOG.md
  check_config/DOCS.md
  check_config/README.md
  check_config/build.json
  check_config/config.json
  check_config/translations/en.yaml
Labels: cla-signed, add-on: check_config

#2199 SSH: Upgrade CLI to 4.14.0
  ssh/CHANGELOG.md
  ssh/build.json
  ssh/config.json
Labels: cla-signed

#2200 Fix typo
  check_config/translations/en.yaml
Labels: add-on: check_config

#2189 Add option for SSL cert algorithm in DuckDNS addon
  duckdns/CHANGELOG.md
  duckdns/DOCS.md
  duckdns/config.json
  duckdns/data/run.sh
Labels: cla-signed, add-on: duckdns

#2157 Add S2 keys support to zwave_js config
  zwave_js/DOCS.md
  zwave_js/config.json
  zwave_js/rootfs/etc/cont-init.d/config.sh
  zwave_js/rootfs/usr/share/tempio/zwave_config.conf
Labels: cla-signed, add-on: zwave_js

#2188 Bump zwave-js and zwave-js-server versions
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed, add-on: zwave_js

#2205 Retain zwave_js legacy network_key config option
  zwave_js/CHANGELOG.md
  zwave_js/config.json
  zwave_js/rootfs/etc/cont-init.d/config.sh
Labels: cla-signed

#2204 Use `=` instead of deprecated `:` as security option separator
  .devcontainer/supervisor.sh
Labels: cla-signed

#2207 Bump zwave-js-server to 1.10.6
  zwave_js/CHANGELOG.md
  zwave_js/build.json
  zwave_js/config.json
Labels: cla-signed

#2208 Properly handle security key casing in zwave_js
  zwave_js/CHANGELOG.md
  zwave_js/config.json
  zwave_js/rootfs/etc/cont-init.d/config.sh
  zwave_js/rootfs/etc/services.d/zwave_js/run
Labels: cla-signed
