Repository home-assistant/addons, pull requests merged in 2022-08, with the labels that each got.

#2609 Update zwave_js docs
  zwave_js/DOCS.md
Labels: cla-signed

#2624 Fix my.home-assistant.io link for Supervisor logs in Issue form
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: cla-signed

#2632 Bump zwave-js to 10.0.1 and zwave-js-server to 1.22.1
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#2570 Support CNAME records
  dnsmasq/CHANGELOG.md
  dnsmasq/DOCS.md
  dnsmasq/config.yaml
  dnsmasq/rootfs/usr/share/tempio/dnsmasq.config
Labels: cla-signed, add-on: dnsmasq

#2635 SSH - Update CLI 4.21.0
  ssh/CHANGELOG.md
  ssh/build.yaml
  ssh/config.yaml
Labels: cla-signed, add-on: ssh, dependencies

#2595 letsencrypt: Add DNS Hetzner provider
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/Dockerfile
  letsencrypt/build.yaml
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed

#2638 Mosquitto improve log timestamp format
  mosquitto/CHANGELOG.md
  mosquitto/config.yaml
  mosquitto/rootfs/usr/share/tempio/mosquitto.gtpl
Labels: cla-signed, add-on: mosquitto

#2639 Bump zwave-js to 10.0.2
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#2637 DNSMasq - default cnames to empty array
  dnsmasq/CHANGELOG.md
  dnsmasq/config.yaml
  dnsmasq/translations/en.yaml
Labels: cla-signed, add-on: dnsmasq

#2643 Bump zwave-js to 10.0.3
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed
