Repository home-assistant/addons, pull requests merged in 2022-04, with the labels that each got.

#2364 Improve GitHub action
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/dependabot.yml
  .github/move.yml
  .github/workflows/builder.yml
  .github/workflows/lint.yml
  .github/workflows/stale.yml
  .hadolint.yaml
  ada/build.yaml
  ada/config.yaml
  almond/build.yaml
  almond/config.yaml
  cec_scan/build.yaml
  cec_scan/config.yaml
  check_config/build.yaml
  check_config/config.yaml
  check_config/translations/en.yaml
  configurator/build.yaml
  configurator/config.yaml
  deconz/build.yaml
  deconz/config.yaml
  dhcp_server/build.yaml
  dhcp_server/config.yaml
  dnsmasq/build.yaml
  dnsmasq/config.yaml
  duckdns/build.yaml
  duckdns/config.yaml
  git_pull/build.yaml
  git_pull/config.yaml
  google_assistant/build.yaml
  google_assistant/config.yaml
  homematic/build.yaml
  homematic/config.yaml
  letsencrypt/build.yaml
  letsencrypt/config.yaml
  mariadb/build.yaml
  mariadb/config.yaml
  mosquitto/build.yaml
  mosquitto/config.yaml
  nginx_proxy/build.yaml
  nginx_proxy/config.yaml
  rpc_shutdown/build.yaml
  rpc_shutdown/config.yaml
  samba/build.yaml
  samba/config.yaml
  ssh/build.yaml
  ssh/config.yaml
  tellstick/build.yaml
  tellstick/config.yaml
  vlc/build.yaml
  vlc/config.yaml
  zwave/build.yaml
  zwave/config.yaml
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#2424 Bump zwave-js to 9.0.2 and zwave-js-server to 1.16.0
  zwave_js/CHANGELOG.md
  zwave_js/Dockerfile
  zwave_js/build.yaml
  zwave_js/config.yaml
  zwave_js/rootfs/etc/services.d/zwave_js/run
Labels: cla-signed

#2445 Bump zwave-js to 9.0.4
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#2422 Add missing discord link to nginx_proxy docs
  nginx_proxy/DOCS.md
Labels: cla-signed

#2353 Enable Samba on all supported interfaces
  samba/CHANGELOG.md
  samba/config.yaml
  samba/rootfs/etc/cont-init.d/samba.sh
  samba/rootfs/usr/share/tempio/smb.gtpl
Labels: cla-signed

#2230 Upgrade certbot; add preferred chain flag
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed, add-on: letsencrypt, hacktoberfest-accepted

#2448 Update changelog and version for #2230
  letsencrypt/CHANGELOG.md
  letsencrypt/config.yaml
Labels: bug, cla-signed, add-on: letsencrypt

#2449 Use HA wheels during build
  letsencrypt/CHANGELOG.md
  letsencrypt/Dockerfile
  letsencrypt/build.yaml
  letsencrypt/config.yaml
Labels: cla-signed, add-on: letsencrypt

#2325 Fix deCONZ/Phoscon Ingress access when using FQDN
  deconz/CHANGELOG.md
  deconz/config.yaml
  deconz/rootfs/etc/nginx/nginx.conf
Labels: cla-signed

#2433 Add translation files to all add-ons
  ada/DOCS.md
  ada/translations/en.yaml
  configurator/translations/en.yaml
  deconz/config.yaml
  deconz/translations/en.yaml
  dhcp_server/translations/en.yaml
  dnsmasq/translations/en.yaml
  duckdns/config.yaml
  duckdns/translations/en.yaml
  git_pull/config.yaml
  git_pull/translations/en.yaml
  google_assistant/config.yaml
  google_assistant/translations/en.yaml
  homematic/config.yaml
  homematic/translations/en.yaml
  letsencrypt/config.yaml
  letsencrypt/translations/en.yaml
  mariadb/config.yaml
  mariadb/translations/en.yaml
  mosquitto/config.yaml
  mosquitto/translations/en.yaml
  nginx_proxy/config.yaml
  nginx_proxy/translations/en.yaml
  rpc_shutdown/translations/en.yaml
  samba/config.yaml
  samba/translations/en.yaml
  ssh/config.yaml
  ssh/translations/en.yaml
  tellstick/translations/en.yaml
  zwave/DOCS.md
  zwave/config.yaml
  zwave/translations/en.yaml
  zwave_js/DOCS.md
  zwave_js/config.yaml
  zwave_js/translations/en.yaml
Labels: cla-signed

#2457 [Samba] Remove lo interface
  samba/CHANGELOG.md
  samba/config.yaml
  samba/rootfs/etc/cont-init.d/samba.sh
Labels: cla-signed
