Repository home-assistant/addons, pull requests merged in 2022-05, with the labels that each got.

#2460 Bump zwave-js to 9.0.7
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#2458 deCONZ 2.15.3 (stable)
  deconz/CHANGELOG.md
  deconz/build.yaml
  deconz/config.yaml
Labels: cla-signed

#2462 Almond3
  almond/CHANGELOG.md
  almond/DOCS.md
  almond/Dockerfile
  almond/README.md
  almond/build.yaml
  almond/config.yaml
  almond/icon.png
  almond/logo.png
  almond/rootfs/etc/genie/default-prefs.db
  almond/rootfs/etc/services.d/almond/run
Labels: cla-signed

#2463 SSH: Update cli 4.17.0
  ssh/CHANGELOG.md
  ssh/build.yaml
  ssh/config.yaml
Labels: cla-signed

#2376 J0hnby dhcp server ntp
  dhcp_server/CHANGELOG.md
  dhcp_server/DOCS.md
  dhcp_server/config.yaml
  dhcp_server/data/run.sh
Labels: cla-signed

#2453 Update mosquitto to 2.0.11
  mosquitto/CHANGELOG.md
  mosquitto/Dockerfile
  mosquitto/build.yaml
  mosquitto/config.yaml
  mosquitto/rootfs/etc/cont-init.d/mosquitto.sh
  mosquitto/rootfs/usr/share/tempio/mosquitto.gtpl
Labels: cla-signed, add-on: mosquitto

#2471 Don't purge openssl
  mosquitto/CHANGELOG.md
  mosquitto/Dockerfile
  mosquitto/config.yaml
Labels: bug, cla-signed, add-on: mosquitto

#2477 Add debug option to mosquitto
  mosquitto/CHANGELOG.md
  mosquitto/DOCS.md
  mosquitto/config.yaml
  mosquitto/rootfs/etc/cont-init.d/mosquitto.sh
  mosquitto/rootfs/usr/share/tempio/mosquitto.gtpl
  mosquitto/translations/en.yaml
Labels: cla-signed

#2492 Bump zwave_js to 9.3.0 and zwave-js-server to 1.17.0
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#2495 Fix zwave_js file permissions issues
  zwave_js/CHANGELOG.md
  zwave_js/config.yaml
  zwave_js/rootfs/etc/cont-init.d/config.sh
  zwave_js/rootfs/etc/cont-init.d/structure.sh
  zwave_js/rootfs/etc/services.d/zwave_js/finish
  zwave_js/rootfs/etc/services.d/zwave_js/run
Labels: cla-signed

#2500 deCONZ 2.16.1 (stable)
  deconz/CHANGELOG.md
  deconz/build.yaml
  deconz/config.yaml
Labels: cla-signed

#2507 deconz: Bump to fix S6 service permissions
  deconz/CHANGELOG.md
  deconz/config.yaml
Labels: cla-signed, add-on: deconz
