Repository home-assistant/addons, pull requests merged in 2023-01, with the labels that each got.

#2829 silabs-multiprotocol: Add OTBR discovery support
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/Dockerfile
  silabs-multiprotocol/Dockerfile.amd64
  silabs-multiprotocol/config.yaml
  silabs-multiprotocol/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent-rest-discovery/dependencies.d/otbr-agent
  silabs-multiprotocol/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent-rest-discovery/type
  silabs-multiprotocol/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent-rest-discovery/up
  silabs-multiprotocol/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/data/check
  silabs-multiprotocol/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/otbr-agent-rest-discovery
  silabs-multiprotocol/rootfs/etc/s6-overlay/scripts/otbr-agent-rest-discovery.sh
Labels: cla-signed

#2833 silabs-multiprotocol: Make HTTP REST server HTTP compliant
  silabs-multiprotocol/0001-web-rest-listen-on-IPv6-addresses-as-well-1659.patch
  silabs-multiprotocol/0002-rest-add-active-dataset-API-1658.patch
  silabs-multiprotocol/0003-rest-use-map-for-HTTP-headers-1665.patch
  silabs-multiprotocol/0005-web-bump-to-latest-Simple-Web-Server-version-1667.patch
  silabs-multiprotocol/0006-rest-allow-to-specify-REST-listen-address-1670.patch
  silabs-multiprotocol/0007-rest-implement-REST-API-to-get-dataset.patch
  silabs-multiprotocol/0008-rest-support-state-change.patch
  silabs-multiprotocol/0009-rest-remove-superfluous-space-in-HTTP-status-line.patch
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/Dockerfile
  silabs-multiprotocol/Dockerfile.amd64
  silabs-multiprotocol/config.yaml
Labels: cla-signed

#2834 silabs-multiprotocol: Make HTTP REST server HTTP compliant part 2
  silabs-multiprotocol/0001-web-rest-listen-on-IPv6-addresses-as-well-1659.patch
  silabs-multiprotocol/0002-rest-add-active-dataset-API-1658.patch
  silabs-multiprotocol/0003-rest-use-map-for-HTTP-headers-1665.patch
  silabs-multiprotocol/0005-web-bump-to-latest-Simple-Web-Server-version-1667.patch
  silabs-multiprotocol/0006-rest-allow-to-specify-REST-listen-address-1670.patch
  silabs-multiprotocol/0007-rest-implement-REST-API-to-get-dataset.patch
  silabs-multiprotocol/0008-rest-support-state-change.patch
  silabs-multiprotocol/0009-rest-remove-superfluous-space-in-HTTP-status-line.patch
  silabs-multiprotocol/0010-rest-explicitly-set-Connection-header-to-close.patch
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/Dockerfile
  silabs-multiprotocol/config.yaml
Labels: cla-signed

#2807 deconz: update path to hardware page
  deconz/DOCS.md
Labels: cla-signed

#2844 Bump Matter Server to 1.1.0
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed

#2842 Bump deconz to 2.20.1
  deconz/CHANGELOG.md
  deconz/build.yaml
  deconz/config.yaml
Labels: cla-signed

#2847 silabs-multiprotocol: Update to Gecko SDK v4.1.4
  silabs-multiprotocol/0001-web-rest-listen-on-IPv6-addresses-as-well-1659.patch
  silabs-multiprotocol/0002-rest-add-active-dataset-API-1658.patch
  silabs-multiprotocol/0003-rest-use-map-for-HTTP-headers-1665.patch
  silabs-multiprotocol/0005-web-bump-to-latest-Simple-Web-Server-version-1667.patch
  silabs-multiprotocol/0006-rest-allow-to-specify-REST-listen-address-1670.patch
  silabs-multiprotocol/0007-rest-implement-REST-API-to-get-dataset.patch
  silabs-multiprotocol/0008-rest-support-state-change.patch
  silabs-multiprotocol/0009-rest-remove-superfluous-space-in-HTTP-status-line.patch
  silabs-multiprotocol/0010-rest-explicitly-set-Connection-header-to-close.patch
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/build.yaml
  silabs-multiprotocol/config.yaml
  silabs-multiprotocol/rootfs/etc/s6-overlay/scripts/universal-silabs-flasher-up
  silabs-multiprotocol/rootfs/root/NabuCasa_RCP_v4.1.4_rcp-uart-hw-802154_115200.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_RCP_v4.2.0_rcp-uart-hw-802154_115200.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.1.4_rcp-uart-hw-802154_115200.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.2.0_rcp-uart-hw-802154_115200.gbl
Labels: cla-signed, add-on: silabs-flasher

#2849 Update list of Add-ons in the issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: cla-signed

#2766 Update DOCS.md
  letsencrypt/DOCS.md
Labels: cla-signed, add-on: letsencrypt

#2659 INWX support added
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/Dockerfile
  letsencrypt/build.yaml
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed, add-on: letsencrypt

#2850 Bump Matter Server to 2.0.1 and set Vendor ID
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
  matter_server/rootfs/etc/s6-overlay/s6-rc.d/matter-server/run
Labels: cla-signed

#2852 Fix matter server fabric id
  matter_server/CHANGELOG.md
  matter_server/config.yaml
  matter_server/rootfs/etc/s6-overlay/s6-rc.d/matter-server/run
Labels: cla-signed

#2854 Bump python-matter-server to 2.0.2
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed

#2858 Bump zwave-js-server to 1.25.0 and zwave-js to 10.5.4
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#2867 Update MariaDB version to 10.6.10
  mariadb/CHANGELOG.md
  mariadb/config.yaml
Labels: cla-signed
