Repository home-assistant/addons, pull requests merged in 2023-04, with the labels that each got.

#2961 Update HomeMatic URLs
  homematic/README.md
Labels: cla-signed

#2962 Fix RPC Shutdown URLs
  rpc_shutdown/DOCS.md
Labels: cla-signed

#2968 silabs-multiprotocol: Fix firmware flashing for amd64
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/Dockerfile.amd64
  silabs-multiprotocol/config.yaml
Labels: cla-signed

#2979 Bump matter server to 3.3.0
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed

#2981 matter_server: Bump Python Matter server to 3.3.1
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed, add-on: matter_server

#2960 Dnsmasq: Added switch that disables dnsmasq "log-queries" parameter
  dnsmasq/CHANGELOG.md
  dnsmasq/DOCS.md
  dnsmasq/config.yaml
  dnsmasq/rootfs/usr/share/tempio/dnsmasq.config
  dnsmasq/translations/en.yaml
Labels: cla-signed, add-on: dnsmasq

#2988 Fix slow startup of dnsmasq on HAOS 10
  dnsmasq/CHANGELOG.md
  dnsmasq/build.yaml
  dnsmasq/config.yaml
  dnsmasq/rootfs/etc/services.d/dnsmasq/run
Labels: cla-signed

#2875 Allow ha commands without an interactive shell
  ssh/CHANGELOG.md
  ssh/config.yaml
  ssh/rootfs/etc/cont-init.d/ssh.sh
  ssh/rootfs/usr/share/tempio/ssh.environment
  ssh/rootfs/usr/share/tempio/sshd_config
Labels: cla-signed

#2837 rpc_shutdown: Allow '%' sign in password
  rpc_shutdown/CHANGELOG.md
  rpc_shutdown/config.yaml
Labels: cla-signed, add-on: rpc_shutdown

#2992 rpc_shutdown: Bump to Alpine 3.17
  rpc_shutdown/CHANGELOG.md
  rpc_shutdown/build.yaml
  rpc_shutdown/config.yaml
  rpc_shutdown/data/run.sh
Labels: cla-signed, add-on: rpc_shutdown

#2993 ssh: Update HA CLI and other add-on dependencies
  ssh/CHANGELOG.md
  ssh/Dockerfile
  ssh/build.yaml
  ssh/config.yaml
Labels: cla-signed

#2913 NGINX: Reload NGINX on certificate renewal
  nginx_proxy/CHANGELOG.md
  nginx_proxy/Dockerfile
  nginx_proxy/config.yaml
  nginx_proxy/rootfs/etc/nginx.conf
  nginx_proxy/rootfs/etc/periodic/daily/check_certificate_renewal
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/crond/dependencies.d/nginx
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/crond/finish
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/crond/run
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/crond/type
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/base
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/nginx/finish
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/nginx/type
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/crond
  nginx_proxy/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/nginx
Labels: cla-signed, add-on: nginx_proxy

#2989 Add piper addon
  piper/CHANGELOG.md
  piper/DOCS.md
  piper/Dockerfile
  piper/README.md
  piper/build.yaml
  piper/config.yaml
  piper/icon.png
  piper/logo.png
  piper/rootfs/etc/s6-overlay/s6-rc.d/discovery/dependencies.d/piper
  piper/rootfs/etc/s6-overlay/s6-rc.d/discovery/run
  piper/rootfs/etc/s6-overlay/s6-rc.d/discovery/type
  piper/rootfs/etc/s6-overlay/s6-rc.d/discovery/up
  piper/rootfs/etc/s6-overlay/s6-rc.d/piper/dependencies.d/base
  piper/rootfs/etc/s6-overlay/s6-rc.d/piper/finish
  piper/rootfs/etc/s6-overlay/s6-rc.d/piper/run
  piper/rootfs/etc/s6-overlay/s6-rc.d/piper/type
  piper/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/discovery
  piper/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/piper
  piper/translations/en.yaml
Labels: cla-signed

#2999 Whisper: disable discovery
  whisper/config.yaml
Labels: cla-signed

#3000 Piper: disable discovery
  piper/config.yaml
Labels: cla-signed

#2995 typo: OCP -> RCP
  openthread_border_router/DOCS.md
Labels: cla-signed

#2997 samba: Update to Alpine 3.17
  samba/CHANGELOG.md
  samba/build.yaml
  samba/config.yaml
Labels: cla-signed, add-on: samba

#2996 configurator: Update Alpine 3.17, S6 migration, add health checks
  configurator/CHANGELOG.md
  configurator/Dockerfile
  configurator/build.yaml
  configurator/config.yaml
  configurator/rootfs/etc/configurator.conf
  configurator/rootfs/etc/s6-overlay/s6-rc.d/configurator/dependencies.d/base
  configurator/rootfs/etc/s6-overlay/s6-rc.d/configurator/finish
  configurator/rootfs/etc/s6-overlay/s6-rc.d/configurator/run
  configurator/rootfs/etc/s6-overlay/s6-rc.d/configurator/type
  configurator/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/configurator
  configurator/rootfs/etc/services.d/configurator/finish
Labels: cla-signed, add-on: configurator

#2976 Bump zwave-js to 10.15.0 and zwave-js-server to 1.28.0
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed, add-on: zwave_js

#3008 VLC: Update to Alpine 3.17 and migrate to new s6-overlay
  vlc/CHANGELOG.md
  vlc/build.yaml
  vlc/config.yaml
  vlc/rootfs/etc/s6-overlay/s6-rc.d/nginx/finish
  vlc/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
  vlc/rootfs/etc/s6-overlay/s6-rc.d/nginx/type
  vlc/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/nginx
  vlc/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/vlc
  vlc/rootfs/etc/s6-overlay/s6-rc.d/vlc/finish
  vlc/rootfs/etc/s6-overlay/s6-rc.d/vlc/run
  vlc/rootfs/etc/s6-overlay/s6-rc.d/vlc/type
  vlc/rootfs/etc/s6-overlay/scripts/vlc-discovery
Labels: cla-signed, add-on: vlc

#3009 piper/whisper: Enable Wyoming protocol discovery
  piper/CHANGELOG.md
  piper/config.yaml
  whisper/CHANGELOG.md
  whisper/config.yaml
Labels: cla-signed

#2987 Mosquitto Addon: Add libcjson1 and libc-ares2 dependency for mosquitto_dynamic_security.so plugin/asynchronous name resolver dependencies
  mosquitto/CHANGELOG.md
  mosquitto/Dockerfile
  mosquitto/config.yaml
Labels: cla-signed, add-on: mosquitto

#3010 Update piper voices for release
  piper/CHANGELOG.md
  piper/DOCS.md
  piper/config.yaml
Labels: cla-signed
