Repository home-assistant/addons, pull requests merged in 2023-07, with the labels that each got.

#3131 Bump Matter Server to 3.6.4
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed

#3134 openthread_border_router: update OTBR and universal-silabs-flasher
  openthread_border_router/0001-rest-initialize-dataset.patch
  openthread_border_router/0001-rest-support-deleting-the-dataset.patch
  openthread_border_router/CHANGELOG.md
  openthread_border_router/Dockerfile
  openthread_border_router/build.yaml
  openthread_border_router/config.yaml
  openthread_border_router/rootfs/etc/s6-overlay/scripts/otbr-agent-rest-discovery.sh
Labels: cla-signed, add-on: openthread_border_router

#3140 silabs-multiprotocol: Add new OTBR reset REST API
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/Dockerfile
  silabs-multiprotocol/build.yaml
  silabs-multiprotocol/config.yaml
  silabs-multiprotocol/otbr-patches/0001-rest-support-Thread-state-change-1866.patch
  silabs-multiprotocol/otbr-patches/0002-rest-initialize-dataset.patch
  silabs-multiprotocol/otbr-patches/0003-rest-deactive-IPv6-interface-when-disabling-the-OTBR.patch
  silabs-multiprotocol/otbr-patches/0004-rest-support-erasing-all-persistent-info-1908.patch
  silabs-multiprotocol/otbr-patches/0005-rest-support-deleting-the-dataset.patch
Labels: cla-signed, add-on: silabs-multiprotocol

#3149 Bump Matter server to 3.7.0
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed

#3148 Bump zwave-js to 11.6.0 and zwave-js-server to 1.30.0
  zwave_js/CHANGELOG.md
  zwave_js/Dockerfile
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed
