Repository home-assistant/addons, pull requests merged in 2023-09, with the labels that each got.

#3187 Update Mosquitto to 2.0.17
  mosquitto/CHANGELOG.md
  mosquitto/build.yaml
  mosquitto/config.yaml
Labels: cla-signed, add-on: mosquitto

#3202 Bump zwave-js to 11.14.0
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#3183 Allow pre-hashed passwords in mosquitto logins config.
  mosquitto/CHANGELOG.md
  mosquitto/DOCS.md
  mosquitto/config.yaml
  mosquitto/rootfs/etc/cont-init.d/mosquitto.sh
  mosquitto/translations/en.yaml
Labels: cla-signed

#3201 nginx_proxy: Improve domain description
  nginx_proxy/DOCS.md
Labels: cla-signed, add-on: nginx_proxy

#3211 Pin actions/checkout dependency to v4.0.0
  .github/workflows/builder.yml
  .github/workflows/lint.yml
Labels: cla-signed

#3225 README.md: Trailing full stops
  README.md
Labels: cla-signed

#3227 Bump zwave-js to 12.0.0 and zwave-js-server to 1.32.0
  zwave_js/CHANGELOG.md
  zwave_js/Dockerfile
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#3229 Re-add rebuilding serialports bindings from src to zwave_js
  zwave_js/CHANGELOG.md
  zwave_js/Dockerfile
  zwave_js/config.yaml
Labels: cla-signed

#3232 Bump zwave-js-server to 1.32.1
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#3228 Add openWakeWord add-on
  openwakeword/CHANGELOG.md
  openwakeword/DOCS.md
  openwakeword/Dockerfile
  openwakeword/README.md
  openwakeword/build.yaml
  openwakeword/config.yaml
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/discovery/dependencies.d/openwakeword
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/discovery/run
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/discovery/type
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/discovery/up
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/openwakeword/dependencies.d/base
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/openwakeword/finish
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/openwakeword/run
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/openwakeword/type
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/discovery
  openwakeword/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/openwakeword
  openwakeword/translations/en.yaml
Labels: cla-signed

#3233 Revert deCONZ to 2.22.2 due to a Phoscon bug
  deconz/CHANGELOG.md
  deconz/build.yaml
  deconz/config.yaml
Labels: cla-signed, add-on: deconz

#3236 Bump to wyoming-openwakeword 1.5.1 for wake word descriptions
  openwakeword/CHANGELOG.md
  openwakeword/build.yaml
  openwakeword/config.yaml
Labels: cla-signed
