Repository home-assistant/addons, pull requests merged in 2024-01, with the labels that each got.

#3382 matter_server: Bump Python Matter server to 5.1.4
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed

#3384 openthread_border_router: Update to OpenThread RCP v4.4.0.0
  openthread_border_router/CHANGELOG.md
  openthread_border_router/Dockerfile
  openthread_border_router/build.yaml
  openthread_border_router/config.yaml
  openthread_border_router/rootfs/etc/s6-overlay/scripts/universal-silabs-flasher-up
  openthread_border_router/rootfs/root/NabuCasa_SkyConnect_OpenThread_RCP_v2.3.1.0_ot-rcp_hw_460800.gbl
  openthread_border_router/rootfs/root/NabuCasa_SkyConnect_OpenThread_RCP_v2.4.0.0_ot-rcp_hw_460800.gbl
  openthread_border_router/rootfs/root/NabuCasa_Yellow_OpenThread_RCP_v2.3.1.0_PA32_ot-rcp_hw_460800.gbl
  openthread_border_router/rootfs/root/NabuCasa_Yellow_OpenThread_RCP_v2.4.0.0_PA32_ot-rcp_hw_460800.gbl
Labels: cla-signed

#3370 silabs-multiprotocol: Update to Gecko SDK v4.4.0
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/Dockerfile
  silabs-multiprotocol/build.yaml
  silabs-multiprotocol/config.yaml
  silabs-multiprotocol/otbr-patches/0001-Avoid-writing-to-system-console.patch
  silabs-multiprotocol/otbr-patches/0001-rest-support-erasing-all-persistent-info-1908.patch
  silabs-multiprotocol/otbr-patches/0002-rest-support-deleting-the-dataset.patch
  silabs-multiprotocol/otbr-patches/0003-mdns-update-mDNSResponder-to-1790.80.10.patch
  silabs-multiprotocol/otbr-patches/0004-mdns-add-Linux-specific-patches.patch
  silabs-multiprotocol/rootfs/etc/s6-overlay/scripts/universal-silabs-flasher-up
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_Yellow_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_Yellow_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
Labels: cla-signed

#3299 feat: add UI configuration, automation, cert usage
  letsencrypt/DOCS.md
Labels: cla-signed, add-on: letsencrypt

#3388 silabs-multiprotocol: Revert to Gecko SDK v4.3.1
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/Dockerfile
  silabs-multiprotocol/build.yaml
  silabs-multiprotocol/config.yaml
  silabs-multiprotocol/otbr-patches/0001-Avoid-writing-to-system-console.patch
  silabs-multiprotocol/otbr-patches/0001-rest-support-erasing-all-persistent-info-1908.patch
  silabs-multiprotocol/otbr-patches/0002-rest-support-deleting-the-dataset.patch
  silabs-multiprotocol/otbr-patches/0003-mdns-update-mDNSResponder-to-1790.80.10.patch
  silabs-multiprotocol/otbr-patches/0004-mdns-add-Linux-specific-patches.patch
  silabs-multiprotocol/rootfs/etc/s6-overlay/scripts/universal-silabs-flasher-up
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_Yellow_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_Yellow_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
Labels: cla-signed

#3392 multiprotocol: Bump flasher so the addon starts
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/build.yaml
  silabs-multiprotocol/config.yaml
Labels: cla-signed

#3389 letsencrypt: fix docs broken by missing closing tag
  letsencrypt/DOCS.md
Labels: cla-signed

#3368 whisper: Exit with error on unsupported CPU (missing AVX)
  whisper/CHANGELOG.md
  whisper/config.yaml
  whisper/rootfs/etc/s6-overlay/s6-rc.d/whisper/run
Labels: cla-signed, add-on: whisper

#3399 nginx_proxy: Support longer domains name
  nginx_proxy/CHANGELOG.md
  nginx_proxy/config.yaml
  nginx_proxy/rootfs/etc/nginx.conf
Labels: cla-signed

#3396 openthread_border_router: Fix TREL and enable channel manager
  openthread_border_router/0001-channel-monitor-disable-by-default.patch
  openthread_border_router/CHANGELOG.md
  openthread_border_router/Dockerfile
  openthread_border_router/build.yaml
  openthread_border_router/config.yaml
  openthread_border_router/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/run
Labels: cla-signed, add-on: openthread_border_router

#3390 Re-release multiprotocol addon with GSDK 4.4.0, targetting Core 2024.1.0+
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/Dockerfile
  silabs-multiprotocol/build.yaml
  silabs-multiprotocol/config.yaml
  silabs-multiprotocol/otbr-patches/0001-Avoid-writing-to-system-console.patch
  silabs-multiprotocol/otbr-patches/0001-rest-support-erasing-all-persistent-info-1908.patch
  silabs-multiprotocol/otbr-patches/0002-rest-support-deleting-the-dataset.patch
  silabs-multiprotocol/otbr-patches/0003-mdns-update-mDNSResponder-to-1790.80.10.patch
  silabs-multiprotocol/otbr-patches/0004-mdns-add-Linux-specific-patches.patch
  silabs-multiprotocol/rootfs/etc/s6-overlay/scripts/universal-silabs-flasher-up
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_Yellow_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_Yellow_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
Labels: cla-signed

#3407 multiprotocol: Bump multiprotocol addon version to 2.4.3
  silabs-multiprotocol/config.yaml
Labels: cla-signed

#3401 letsencrypt: Add support for ClouDNS provider
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/Dockerfile
  letsencrypt/build.yaml
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed, cla-error

#3414 matter_server: Bump Python Matter server to 5.2.1
  matter_server/CHANGELOG.md
  matter_server/config.yaml
  matter_server/rootfs/etc/s6-overlay/s6-rc.d/matter-server/run
Labels: cla-signed

#3423 matter_server: Bump Python Matter server to 5.2.1 correctly
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed

#3409 letsencrypt: Add support for Hurricane Electric
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/Dockerfile
  letsencrypt/build.yaml
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed, add-on: letsencrypt

#3426 openthread_border_router: Fix Thread netif route metric
  openthread_border_router/0003-openthread-set-netif-route-metric-lower.patch
  openthread_border_router/CHANGELOG.md
  openthread_border_router/Dockerfile
  openthread_border_router/build.yaml
  openthread_border_router/config.yaml
Labels: cla-signed, add-on: openthread_border_router

#3421 letsencrypt ClouDNS bug fix and build fix
  letsencrypt/CHANGELOG.md
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
Labels: cla-signed

#3428 Clean up Genie add-on
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  almond/CHANGELOG.md
  almond/DOCS.md
  almond/Dockerfile
  almond/README.md
  almond/build.yaml
  almond/config.yaml
  almond/icon.png
  almond/logo.png
  almond/rootfs/etc/genie/default-prefs.db
  almond/rootfs/etc/nginx/nginx.conf
  almond/rootfs/etc/services.d/almond/discovery
  almond/rootfs/etc/services.d/almond/finish
  almond/rootfs/etc/services.d/almond/register
  almond/rootfs/etc/services.d/almond/run
  almond/rootfs/etc/services.d/nginx/finish
  almond/rootfs/etc/services.d/nginx/run
Labels: cla-signed, add-on: almond

#3430 Clean up OpenZWave add-on
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  zwave/CHANGELOG.md
  zwave/DOCS.md
  zwave/Dockerfile
  zwave/README.md
  zwave/build.yaml
  zwave/config.yaml
  zwave/icon.png
  zwave/logo.png
  zwave/rootfs/etc/cont-finish.d/mqtt.sh
  zwave/rootfs/etc/cont-init.d/auth.sh
  zwave/rootfs/etc/cont-init.d/mqtt.sh
  zwave/rootfs/etc/cont-init.d/network_key.sh
  zwave/rootfs/etc/cont-init.d/novnc.sh
  zwave/rootfs/etc/cont-init.d/structure.sh
  zwave/rootfs/etc/mosquitto.conf
  zwave/rootfs/etc/services.d/mosquitto/finish
  zwave/rootfs/etc/services.d/mosquitto/run
  zwave/rootfs/etc/services.d/ozwadmin/finish
  zwave/rootfs/etc/services.d/ozwadmin/run
  zwave/rootfs/etc/services.d/websockify/finish
  zwave/rootfs/etc/services.d/websockify/run
  zwave/rootfs/etc/services.d/zwave/discovery
  zwave/rootfs/etc/services.d/zwave/finish
  zwave/rootfs/etc/services.d/zwave/run
  zwave/rootfs/usr/lib/mqtt_helper.sh
  zwave/translations/en.yaml
Labels: cla-signed, add-on: zwave

#3429 silabs-multiprotocol: Downgrade GSDK back to v4.3.1
  silabs-multiprotocol/CHANGELOG.md
  silabs-multiprotocol/Dockerfile
  silabs-multiprotocol/build.yaml
  silabs-multiprotocol/config.yaml
  silabs-multiprotocol/otbr-patches/0001-Avoid-writing-to-system-console.patch
  silabs-multiprotocol/otbr-patches/0001-rest-support-erasing-all-persistent-info-1908.patch
  silabs-multiprotocol/otbr-patches/0002-rest-support-deleting-the-dataset.patch
  silabs-multiprotocol/otbr-patches/0003-mdns-update-mDNSResponder-to-1790.80.10.patch
  silabs-multiprotocol/otbr-patches/0004-mdns-add-Linux-specific-patches.patch
  silabs-multiprotocol/rootfs/etc/s6-overlay/scripts/universal-silabs-flasher-up
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_SkyConnect_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_Yellow_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
  silabs-multiprotocol/rootfs/root/NabuCasa_Yellow_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
Labels: cla-signed

#3424 letsencrypt: Default to RSA and allow ECDSA curve selection
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
  letsencrypt/translations/en.yaml
Labels: cla-signed, add-on: letsencrypt

#3435 letsencrypt: Update docs for key_type setting
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/config.yaml
  letsencrypt/translations/en.yaml
Labels: cla-signed, add-on: letsencrypt

#3433 letsencrypt: Add netcup configuration example via DNS
  letsencrypt/DOCS.md
Labels: cla-signed, add-on: letsencrypt

#3438 openthread_border_router: Enable DNS resolver and increase TX power
  openthread_border_router/CHANGELOG.md
  openthread_border_router/build.yaml
  openthread_border_router/config.yaml
  openthread_border_router/rootfs/etc/s6-overlay/scripts/otbr-agent-configure.sh
  openthread_border_router/translations/en.yaml
Labels: cla-signed, add-on: openthread_border_router
