Repository home-assistant/addons, pull requests merged in 2024-11, with the labels that each got.

#3819 Bump zwavejs to 13.10.3
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#3804 Update nginx.conf.gtpl to suppress: 'listen ... http2' directive is deprecated
  nginx_proxy/CHANGELOG.md
  nginx_proxy/config.yaml
  nginx_proxy/rootfs/etc/nginx/nginx.conf.gtpl
Labels: cla-signed, Hacktoberfest

#3807 universal-silabs-flasher: Bump flasher and firmwares
  silabs_flasher/CHANGELOG.md
  silabs_flasher/build.yaml
  silabs_flasher/config.yaml
  silabs_flasher/rootfs/etc/s6-overlay/scripts/universal-silabs-flasher-up
  silabs_flasher/rootfs/root/skyconnect_ncp-uart-hw_7.4.3.0.gbl
  silabs_flasher/rootfs/root/skyconnect_zigbee_ncp_7.4.4.0.gbl
  silabs_flasher/rootfs/root/yellow_ncp-uart-hw_7.4.3.0.gbl
  silabs_flasher/rootfs/root/yellow_zigbee_ncp_7.4.4.0.gbl
Labels: cla-signed, Hacktoberfest, add-on: silabs-flasher

#3828 letsencrypt: Bump certbot-dns-directadmin to 1.0.12
  letsencrypt/CHANGELOG.md
  letsencrypt/build.yaml
  letsencrypt/config.yaml
Labels: cla-signed, add-on: letsencrypt

#3838 Fix dns-loopia username error
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed
