Repository home-assistant/addons, pull requests merged in 2024-10, with the labels that each got.

#3783 nginx: Update to Alpine Linux 3.20 (nginx 1.26.x)
  nginx_proxy/CHANGELOG.md
  nginx_proxy/build.yaml
  nginx_proxy/config.yaml
Labels: cla-signed, Hacktoberfest

#3789 matter_server: Bump Python Matter server to 6.6.0
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed, Hacktoberfest, add-on: matter_server

#3782 Fix otbr for USB cc2652 dongles
  openthread_border_router/CHANGELOG.md
  openthread_border_router/config.yaml
  openthread_border_router/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/run
Labels: cla-signed, Hacktoberfest

#3795 Update wyoming-whisper to 2.2.0
  whisper/CHANGELOG.md
  whisper/build.yaml
  whisper/config.yaml
Labels: cla-signed, Hacktoberfest

#3769 Bump zwave-js to 13.9.0 and add watchdog configuration option
  zwave_js/CHANGELOG.md
  zwave_js/DOCS.md
  zwave_js/build.yaml
  zwave_js/config.yaml
  zwave_js/rootfs/etc/cont-init.d/config.sh
  zwave_js/translations/en.yaml
Labels: cla-signed

#3777 Add note that anonymous logins are not supported to mosquitto/DOCS.md
  mosquitto/DOCS.md
Labels: cla-signed

#3743 Add support for IONOS DNS challenge
  letsencrypt/CHANGELOG.md
  letsencrypt/DOCS.md
  letsencrypt/Dockerfile
  letsencrypt/build.yaml
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/cont-init.d/file-structure.sh
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed, add-on: letsencrypt

#3799 LetsEncrypt - GoDaddy Documentation
  letsencrypt/DOCS.md
Labels: cla-signed, Hacktoberfest

#3800 Fix LetsEncrypt add-on - IONOS syntax error
  letsencrypt/CHANGELOG.md
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed
