Repository home-assistant/addons, pull requests merged in 2025-05, with the labels that each got.

#4006 Fix trust store when using a custom ACME server
  letsencrypt/CHANGELOG.md
  letsencrypt/config.yaml
  letsencrypt/rootfs/etc/services.d/lets-encrypt/run
Labels: cla-signed

#3988 whisper: Improve support for local custom Whisper models
  whisper/CHANGELOG.md
  whisper/DOCS.md
  whisper/config.yaml
Labels: cla-signed, add-on: whisper

#4008 Bump Z-Wave JS to 15.3.0 and Z-Wave JS Server to 3.0.1
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#4012 Bump Z-Wave JS to 15.3.2 and Z-Wave JS Server to 3.0.2
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#4013 Bump deCONZ to v2.30.2
  deconz/CHANGELOG.md
  deconz/build.yaml
  deconz/config.yaml
Labels: cla-signed, add-on: deconz

#4016 Remove incorrect `--find-links` arguments that were being passed to pip
  letsencrypt/Dockerfile
  silabs_flasher/Dockerfile
Labels: cla-signed

#4018 MOSQUITTO v2.0.21
  mosquitto/CHANGELOG.md
  mosquitto/build.yaml
  mosquitto/config.yaml
Labels: cla-signed

#4023 Update to wyoming-piper 1.5.4
  piper/CHANGELOG.md
  piper/build.yaml
  piper/config.yaml
Labels: cla-signed

#4025 matter_server: Bump Python Matter server to 8.0.0
  matter_server/CHANGELOG.md
  matter_server/build.yaml
  matter_server/config.yaml
Labels: cla-signed, add-on: matter_server
