Repository home-assistant/addons, pull requests merged in 2025-07, with the labels that each got.

#4059 Update nginx_proxy to Alpine 3.22, current Mozilla intermediate config
  nginx_proxy/build.yaml
  nginx_proxy/config.yaml
  nginx_proxy/rootfs/etc/nginx/nginx.conf.gtpl
Labels: cla-signed

#4063 letsencrypt: Make sure all build arguments are strings
  letsencrypt/build.yaml
Labels: cla-signed, add-on: letsencrypt

#4074 Add Task issue form
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/task.yml
  .github/workflows/restrict-task-creation.yml
Labels: cla-signed

#4078 Bump Z-Wave JS to 15.9.0
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#4084 Bump Z-Wave JS to 15.10.0
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#4094 Bump Z-Wave JS Server to 3.2.1
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#3833 Deprecate multiprotocol
  silabs-multiprotocol/Dockerfile
  silabs-multiprotocol/README.md
  silabs-multiprotocol/build.yaml
  silabs-multiprotocol/config.yaml
Labels: cla-signed, add-on: silabs-multiprotocol
