Repository home-assistant/addons, pull requests merged in 2025-04, with the labels that each got.

#3966 Replace DWM with Openbox window manager for deCONZ addon
  deconz/CHANGELOG.md
  deconz/Dockerfile
  deconz/config.yaml
Labels: cla-signed, add-on: deconz

#3969 Bump Z-Wave JS to 15.0.5 and Z-Wave JS Server to 3.0.0
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#3979 Wait for TXT record to propagate
  duckdns/CHANGELOG.md
  duckdns/config.yaml
  duckdns/rootfs/root/hooks.sh
Labels: cla-signed, add-on: duckdns

#3985 Avoid ordering deprecated add-ons first
  dhcp_server/config.yaml
  google_assistant/config.yaml
  tellstick/config.yaml
Labels: cla-signed

#3990 fix typo in readme.md for lets encrypt
  README.md
Labels: cla-signed, add-on: letsencrypt

#3987 letsencrypt: Bump certbot-dns-directadmin to 1.0.15
  letsencrypt/CHANGELOG.md
  letsencrypt/build.yaml
  letsencrypt/config.yaml
Labels: cla-signed, add-on: letsencrypt

#3997 Bump Z-Wave JS to 15.1.0
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#4004 Bump Z-Wave JS to 15.1.3
  zwave_js/CHANGELOG.md
  zwave_js/build.yaml
  zwave_js/config.yaml
Labels: cla-signed

#3970 Samba: Make the vfs objects entry in smb.conf optional
  samba/CHANGELOG.md
  samba/DOCS.md
  samba/config.yaml
  samba/rootfs/usr/share/tempio/smb.gtpl
  samba/translations/en.yaml
Labels: cla-signed, add-on: samba
