Repository home-assistant/addons, pull requests merged in 2025-06, with the labels that each got.

#4009 Add Z-Wave region option
  zwave_js/CHANGELOG.md
  zwave_js/DOCS.md
  zwave_js/config.yaml
  zwave_js/rootfs/etc/cont-init.d/config.sh
  zwave_js/rootfs/usr/share/tempio/zwave_config.conf
  zwave_js/translations/en.yaml
Labels: cla-signed

#4043 Add Z-Wave JS power level config
  zwave_js/CHANGELOG.md
  zwave_js/config.yaml
  zwave_js/rootfs/etc/cont-init.d/config.sh
  zwave_js/rootfs/usr/share/tempio/zwave_config.conf
Labels: cla-signed

#4045 correct provider name for dnsimple in example in docs
  letsencrypt/DOCS.md
Labels: cla-signed, add-on: letsencrypt

#4054 samba: Bind on enabled interfaces only
  samba/CHANGELOG.md
  samba/config.yaml
  samba/rootfs/etc/s6-overlay/s6-rc.d/init-smbd/run
  samba/rootfs/usr/share/tempio/smb.gtpl
Labels: cla-signed, add-on: samba

#4055 Add streaming support to Piper
  piper/CHANGELOG.md
  piper/DOCS.md
  piper/build.yaml
  piper/config.yaml
  piper/rootfs/etc/s6-overlay/s6-rc.d/piper/run
  piper/translations/en.yaml
Labels: cla-signed

#4062 Update speech-to-phrase to 1.4.0
  speech_to_phrase/CHANGELOG.md
  speech_to_phrase/DOCS.md
  speech_to_phrase/build.yaml
  speech_to_phrase/config.yaml
Labels: cla-signed
